### PR TITLE
AVRO-3236: Retire .NET Core 2.1

### PR DESCRIPTION
**Pull request by zcsizmadia**
Make sure you have checked _all_ steps below.

### Jira

- [X] My PR addresses the following [Avro Jira](https://issues.apache.org/jira/browse/AVRO-3236)
  - https://issues.apache.org/jira/browse/AVRO-3236
  - In case you are adding a dependency, check if the license complies with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).

### Tests

- [X] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

### Commits

- [X] My commits all reference Jira issues in their subject lines. In addition, my commits follow the guidelines from "[How to write a good git commit message](https://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [X] In case of new functionality, my PR adds documentation that describes how to use it.
  - All the public functions and the classes in the PR contain Javadoc that explain what it does

### References
#1366

### CODE REVIEW

**Comment by RyanSkraba** [comment]
Hey thanks so much!  This looks like it fixes all of the Windows issues.  I gave it a clean build a try on a VM with Visual Studio 2019 installed: 


```
Build started...
1>------ Build started: Project: Avro.main, Configuration: Debug Any CPU ------
1>Avro.main -> C:\Users\rskraba\Documents\avro\lang\csharp\src\apache\main\bin\Debug\netstandard2.1\Avro.dll
2>------ Build started: Project: Avro.test, Configuration: Debug Any CPU ------
3>------ Build started: Project: Avro.codegen, Configuration: Debug Any CPU ------
3>Avro.codegen -> C:\Users\rskraba\Documents\avro\lang\csharp\src\apache\codegen\bin\Debug\net5.0\avrogen.dll
3>Avro.codegen -> C:\Users\rskraba\Documents\avro\lang\csharp\src\apache\codegen\bin\Debug\netcoreapp3.1\avrogen.dll
4>------ Build started: Project: Avro.msbuild, Configuration: Debug Any CPU ------
4>Avro.msbuild -> C:\Users\rskraba\Documents\avro\lang\csharp\src\apache\msbuild\bin\Debug\net461\Avro.msbuild.dll
2>Avro.test -> C:\Users\rskraba\Documents\avro\lang\csharp\src\apache\test\bin\Debug\netcoreapp3.1\Avro.test.dll
2>Avro.test -> C:\Users\rskraba\Documents\avro\lang\csharp\src\apache\test\bin\Debug\net461\Avro.test.dll
2>Avro.test -> C:\Users\rskraba\Documents\avro\lang\csharp\src\apache\test\bin\Debug\net5.0\Avro.test.dll
4>Avro.msbuild -> C:\Users\rskraba\Documents\avro\lang\csharp\src\apache\msbuild\bin\Debug\netstandard2.0\Avro.msbuild.dll
5>------ Build started: Project: Avro.perf, Configuration: Debug Any CPU ------
5>Avro.perf -> C:\Users\rskraba\Documents\avro\lang\csharp\src\apache\perf\bin\Debug\net461\Avro.perf.exe
5>Avro.perf -> C:\Users\rskraba\Documents\avro\lang\csharp\src\apache\perf\bin\Debug\net5.0\Avro.perf.dll
========== Build: 5 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========
```
As well as the command line build in Windows:
```
rskraba@VisualStudio MINGW64 ~/My Documents/avro/lang/csharp (avro__pr1375)
$ ./build.sh clean
++ dirname ./build.sh
+ cd .
+ ROOT=../..
++ cat ../../share/VERSION.txt
+ VERSION=1.12.0-SNAPSHOT
+ for target in "$@"
+ case "$target" in
+ rm -rf src/apache/main/obj src/apache/main/bin src/apache/test/obj src/apache/test/bin src/apache/codegen/obj src/apache/codegen/bin src/apache/ipc/obj src/apache/ipc/bin src/apache/msbuild/obj src/apache/msbuild/bin src/apache/perf/obj src/apache/perf/bin
+ rm -rf build
+ rm -f TestResult.xml

rskraba@VisualStudio MINGW64 ~/My Documents/avro/lang/csharp (avro__pr1375)
$ ./build.sh test
++ dirname ./build.sh
+ cd .
+ ROOT=../..
++ cat ../../share/VERSION.txt
+ VERSION=1.12.0-SNAPSHOT
+ for target in "$@"
+ case "$target" in
+ dotnet build --configuration Release Avro.sln
Microsoft (R) Build Engine version 16.11.1+3e40a09f8 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  Restored C:\Users\rskraba\My Documents\avro\lang\csharp\src\apache\test\Avro.test.csproj (in 817 ms).
  Restored C:\Users\rskraba\My Documents\avro\lang\csharp\src\apache\main\Avro.main.csproj (in 793 ms).
  Restored C:\Users\rskraba\My Documents\avro\lang\csharp\src\apache\codegen\Avro.codegen.csproj (in 49 ms).
  Restored C:\Users\rskraba\My Documents\avro\lang\csharp\src\apache\msbuild\Avro.msbuild.csproj (in 117 ms).
  Restored C:\Users\rskraba\My Documents\avro\lang\csharp\src\apache\perf\Avro.perf.csproj (in 407 ms).
  Avro.main -> C:\Users\rskraba\My Documents\avro\lang\csharp\src\apache\main\bin\Release\netstandard2.0\Avro.dll
  Avro.main -> C:\Users\rskraba\My Documents\avro\lang\csharp\src\apache\main\bin\Release\netstandard2.1\Avro.dll
  Avro.perf -> C:\Users\rskraba\My Documents\avro\lang\csharp\src\apache\perf\bin\Release\net5.0\Avro.perf.dll
  Avro.test -> C:\Users\rskraba\My Documents\avro\lang\csharp\src\apache\test\bin\Release\netcoreapp3.1\Avro.test.dll
  Avro.codegen -> C:\Users\rskraba\My Documents\avro\lang\csharp\src\apache\codegen\bin\Release\net5.0\avrogen.dll
  Avro.test -> C:\Users\rskraba\My Documents\avro\lang\csharp\src\apache\test\bin\Release\net5.0\Avro.test.dll
  Avro.codegen -> C:\Users\rskraba\My Documents\avro\lang\csharp\src\apache\codegen\bin\Release\netcoreapp3.1\avrogen.dll
  Avro.perf -> C:\Users\rskraba\My Documents\avro\lang\csharp\src\apache\perf\bin\Release\net461\Avro.perf.exe
  Avro.msbuild -> C:\Users\rskraba\My Documents\avro\lang\csharp\src\apache\msbuild\bin\Release\netstandard2.0\Avro.msbuild.dll
  Avro.msbuild -> C:\Users\rskraba\My Documents\avro\lang\csharp\src\apache\msbuild\bin\Release\net461\Avro.msbuild.dll
  Avro.test -> C:\Users\rskraba\My Documents\avro\lang\csharp\src\apache\test\bin\Release\net461\Avro.test.dll

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:37.47
+ LANG=en_US.UTF-8
+ dotnet test --configuration Release --no-build --filter 'TestCategory!=Interop' Avro.sln
Test run for C:\Users\rskraba\My Documents\avro\lang\csharp\src\apache\test\bin\Release\net461\Avro.test.dll (.NETFramework,Version=v4.6.1)
Microsoft (R) Test Execution Command Line Tool Version 16.11.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
A total of 1 test files matched the specified pattern.

Passed!  - Failed:     0, Passed:   624, Skipped:     0, Total:   624, Duration: 5 s - Avro.test.dll (net461)
Test run for C:\Users\rskraba\My Documents\avro\lang\csharp\src\apache\test\bin\Release\netcoreapp3.1\Avro.test.dll (.NETCoreApp,Version=v3.1)
Microsoft (R) Test Execution Command Line Tool Version 16.11.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
A total of 1 test files matched the specified pattern.

Passed!  - Failed:     0, Passed:   618, Skipped:     0, Total:   618, Duration: 1 s - Avro.test.dll (netcoreapp3.1)
Test run for C:\Users\rskraba\My Documents\avro\lang\csharp\src\apache\test\bin\Release\net5.0\Avro.test.dll (.NETCoreApp,Version=v5.0)
Microsoft (R) Test Execution Command Line Tool Version 16.11.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
A total of 1 test files matched the specified pattern.

Passed!  - Failed:     0, Passed:   617, Skipped:     0, Total:   617, Duration: 1 s - Avro.test.dll (net5.0)
```

This LGTM -- I'm giving a full build with https://github.com/apache/avro/pull/1357 a try -- @zcsizmadia can you give an opinion on that PR?  If we can merge both, we can probably do a 1.11.0 RC2 !

**Comment by RyanSkraba** [comment]
Thanks for the doc addition.  Your properties proposal sounds great to me, but I'm coming from a very "beginner" perspective, where I have to check each time the relationship between .NET Framework, Core and Standard!  If there's no compelling reason to target different ones for each C# artifact, that would simplify my understanding!

Would it be possible to do that in a secondary JIRA and PR to target 1.11.1 ?  I'd really like to start wrapping up the 1.11.0 release candidate 2!

**Comment by zcsizmadia** [comment]
> Thanks for the doc addition. Your properties proposal sounds great to me, but I'm coming from a very "beginner" perspective, where I have to check each time the relationship between .NET Framework, Core and Standard! If there's no compelling reason to target different ones for each C# artifact, that would simplify my understanding!
> 
> Would it be possible to do that in a secondary JIRA and PR to target 1.11.1 ? I'd really like to start wrapping up the 1.11.0 release candidate 2!

That sounds good. I will make a PR after 11.0 is out. If it is ok, I can make a new PR for this, it will be easier to see the changes and the impacts.

Btw, is anything built in Windows for a release, or all artifacts pushed to nuget.org are built by the linux based github images?

**Comment by martin-g** [comment]
@KyleSchoonover has some further suggestions about the supported versions at the dev@ mailing list: https://lists.apache.org/thread/9k2hztd3jnojkl3z7x6321d5tkrdyn0p

**Comment by KyleSchoonover** [comment]
@zcsizmadia I can dig into the performance gains.  The reason in the email thread was to basically drop support for .Net Framework 4.6.x and above.  As for as I can tell. 4.8 will more than likely be the last version of that framework.  A lot of the performance gains we are going to see is in how we implement and take advantage of the new features.  There are some passive gains.  Typically it has been my experience that we see a performance gain by just upgrading the framework.

Reference for perf improvements by just going to .Net 5: https://devblogs.microsoft.com/dotnet/performance-improvements-in-net-5/

**Comment by zcsizmadia** [comment]
IMO NET Framework support cannot be dropped. It is planned to be supported foo many years to come. IIRC I saw  a graph which showed past 2029 (since it is tied to Windows OS support).

As I said earlier, if a performance gain can be proven, a framework should be added. Honestly it should not be that hard to replace the perf project with something more up to date benchmarking framework, e.g. BenchmarkDotNet.

**Pull request merged**
