### PR TITLE
AVRO-4015: [C++] 

### PR DESCRIPTION
**Pull request by jinxidoru**
## What is the purpose of the change
Currently it's not possible to attach avro-cpp to a project using FetchContent(). This makes that possible.

## Verifying this change
I'm not sure if this is the sort of change that would necessitate test coverage since it is wholly within the cmake file. I am currently using a project that is pointing to this commit within FetchContent:

```
FetchContent_Declare(avrocpp
  GIT_REPOSITORY https://github.com/jinxidoru/avro.git
  GIT_TAG 68a1ab3746716c340ac5361b3a4c6e77e1635cbe
  EXCLUDE_FROM_ALL
  SOURCE_SUBDIR lang/c++)
```

## Documentation
There is no new documentation, though I'm happy to add some if you would like. I'd just need to be told where specifically to add it.

### CODE REVIEW

**Comment by martin-g** [comment]
I like the renaming of `api/` to `include/avro/` ! 
But I am not sure how much breaking this change is.
// CC @Gerrit0 @mkmkme

**Review by mkmkme — APPROVED** [review]
Looks good to me, as the author also handled the renaming in the `install()` directive of CMake. Let's hear from @Gerrit0 as well, though

**Review by Gerrit0 — APPROVED** [review]
Yes! This is a really good change as it makes it possible to add a build step for the examples without installing avro. I was actually planning on doing this once my wconversion branch was merged, as I noticed the examples couldn't be compiled without doing an install with the headers in the api folder.

This might break some people, I know it'll break my build script for avro at work, but that's just because I had to hack avro's target somewhat to make it build for unrelated reasons, and is trivial to fix. Anyone using the regular install target should be unaffected.
(The change to add libfmt from another PR actually breaks me far more than this will, as I have to get another third party approved...)

**Comment by jinxidoru** [comment]
@Gerrit0 - Would it be possible to wise to add a cmake option to determine whether or not to include libfmt? Though I'll admit that I'm a bit unclear how you could be using the library without the libfmt dependency.

**Comment by Gerrit0** [comment]
Before libfmt, avro used boost's format. I've been meaning to look at trying to use C++20's `<format>` first, and falling back to libfmt if not available, but haven't gotten around to it yet.

**Comment by mkmkme** [comment]
@Gerrit0 I can look into it if you want

**Comment by Gerrit0** [comment]
That'd be awesome!

**Comment by martin-g** [comment]
What should we do with this PR ?
Please use Github UI's `Approve` functionality so we (non-C++ devs) know that it is good to be merged! Thanks!

**Comment by martin-g** [comment]
Actually both @mkmkme and @Gerrit0 approved it! Sorry, I had to scroll ... :-)

**Comment by martin-g** [comment]
Thank you, @jinxidoru !

**Comment by jinxidoru** [comment]
> @Gerrit0 I can look into it if you want (I am also the author of PR introducing fmt)

I spent a little time trying to get it working with format last night but I was running into some strange errors. Then I got tired.

**Pull request merged**
