### PR TITLE
AVRO-3304: Use slf4j-simple in avro-tool uberjar

### PR DESCRIPTION
**Pull request by RyanSkraba**
Before:

```
avrotool_snap tojson ./lang/java/mapred/target/test-classes/org/apache/avro/mapreduce/mapreduce-test-input.avro/part-r-00000.avro
22/01/13 18:47:32 WARN util.NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
{"name":"apple","count":3}
{"name":"banana","count":2}
{"name":"carrot","count":1}
```

After: 
```
avrotool_snap tojson ./lang/java/mapred/target/test-classes/org/apache/avro/mapreduce/mapreduce-test-input.avro/part-r-00000.avro
[main] WARN org.apache.hadoop.util.NativeCodeLoader - Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
{"name":"apple","count":3}
{"name":"banana","count":2}
{"name":"carrot","count":1}
```

### Jira

- [X] My PR addresses the following [Avro Jira](https://issues.apache.org/jira/browse/AVRO/) issues and references them in the PR title. For example, "AVRO-1234: My Avro PR"
  - https://issues.apache.org/jira/browse/AVRO-3304
  - In case you are adding a dependency, check if the license complies with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).

### Tests

- [X] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:  Manually verified the change:

### Commits

- [X] My commits all reference Jira issues in their subject lines. In addition, my commits follow the guidelines from "[How to write a good git commit message](https://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [ ] In case of new functionality, my PR adds documentation that describes how to use it.
  - All the public functions and the classes in the PR contain Javadoc that explain what it does

### CODE REVIEW

**Comment by martin-g** [comment]
I think it would be good to add simplelogger.properties to re-add the datetime and set the default log level at least.
See https://github.com/apache/wicket/blob/master/wicket-core/src/test/java/simplelogger.properties

**Comment by RyanSkraba** [comment]
I've added the `simplelogger properties`, and also restored the `log4j.properties`.  Log4j is used by hadoop, so it's worthwhile keeping the two consistent.

**Comment by RyanSkraba** [comment]
I've converted this to draft -- this may not be the right solution (see the JIRA AVRO-3304, log4j-1.2.17 is included in the uberjar as a transitive dependency of hadoop).

**Comment by martin-g** [comment]
Then maybe switch to https://github.com/qos-ch/reload4j ?
https://search.maven.org/artifact/ch.qos.reload4j/reload4j/1.2.18.0/jar

**Comment by RyanSkraba** [comment]
I like the reload4j solution, since it's the only *actual* fix (short of dropping the Hadoop file system functionality or waiting for Hadoop to bump to log4j2)!

**Comment by martin-g** [comment]
https://github.com/apache/avro/pull/1464 (reload4j) is merged!

**Pull request closed without merging**
