### PR TITLE
AVRO-2377: Remove Reserved Words Initialization Blocks

### PR DESCRIPTION
**Pull request by BELUGABEHR**
https://jira.apache.org/jira/browse/AVRO-2377

### CODE REVIEW

**Comment by Fokko** [comment]
CI Failure looks unrelated, I've restarted Travis.

**Comment by nandorKollar** [comment]
Travis is still complaining, this time it seems more related. I guess a spotless:apply is still missing no?

**Comment by Fokko** [comment]
Looks like it:
```
[ERROR] Failed to execute goal com.diffplug.spotless:spotless-maven-plugin:1.21.1:check (spotless-check) on project avro: The following files had format violations:
[ERROR] src/main/java/org/apache/avro/Protocol.java
```

@BELUGABEHR Can you perform a `mvn spotless:apply`?

**Comment by BELUGABEHR** [comment]
@Fokko It's going to take me a few failed attempts to remember to apply `spotless`.  Thanks for alerting me to this issue.  I have pushed new changes.

**Pull request merged**
