### PR TITLE
AVRO-3904: [Rust] Change the return type of SchemaCompatibility::can_read() from `bool` to `AvroResult<()>`

### PR DESCRIPTION
**Pull request by martin-g**
AVRO-3904

**API break**

## What is the purpose of the change

* Do not panic when schemata are incompatible. Return Err and let the user deal with it.

## Verifying this change

* Run the build and test

## Documentation

- Does this pull request introduce a new feature? no

### CODE REVIEW

**Comment by martin-g** [comment]
The unit tests still fail! Needs debugging!

**Comment by marcosschroh** [comment]
This looks really similar to https://github.com/apache/avro/compare/main...marcosschroh:avro:fix/compatibility-read-when-field-is-subset?expand=1. I push literal an hour ago, I stopped to solve an issue in my personal work and I see this... I have never seen such a thing... incredible

**Comment by marcosschroh** [comment]
Next time I will make sure to create a PR a microsecond after pushing to my fork to avoid  people stealing things. This one would have been my first contribution to a project using `rust` as I am a newie in `rust` , thanks a lot @martin-g really appreciate it.

**Comment by martin-g** [comment]
> Next time I will make sure to create a PR a microsecond after pushing to my fork to avoid people stealing things. This one would have been my first contribution to a project using `rust` as I am a newie in `rust` , thanks a lot @martin-g really appreciate it.

Sorry for stealing your joy! :-)
I had free time and decided to work on this...

**Comment by martin-g** [comment]
@marcosschroh You can still review and approve the PR! Thanks!

**Comment by marcosschroh** [comment]
As I mentioned: `I am a newbie in rust`, so another person with more experience should look at it. Despite my lack of knowledge on `rust`, yesterday we agreed in the [jira ticket](https://issues.apache.org/jira/browse/AVRO-3904) that I had to send a PR and then you (@martin-g ) would look at it (not the other way around). Involve another developer with rust experience to get feedback.

**Comment by martin-g** [comment]
I have no time for drama!
I will close the PR and let you open a new one!

**Pull request closed without merging**
