### PR TITLE
AVRO-3322: Buffer is not defined in browser environment

### PR DESCRIPTION
**Pull request by ruleeeer**
Make sure you have checked _all_ steps below.

### Jira

- [x] My PR addresses the following [Avro Jira](https://issues.apache.org/jira/browse/AVRO/) issues and references them in the PR title. For example, "AVRO-3322:Buffer is not defined in browser environment"
  - https://issues.apache.org/jira/browse/AVRO-3322
  - In case you are adding a dependency, check if the license complies with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).

### Tests

- [x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:
- PR simply adds declarations that do not change the actual code logic

### Commits

- [x] My commits all reference Jira issues in their subject lines. In addition, my commits follow the guidelines from "[How to write a good git commit message](https://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [x] In case of new functionality, my PR adds documentation that describes how to use it.
  - All the public functions and the classes in the PR contain Javadoc that explain what it does

### CODE REVIEW

**Comment by martin-g** [comment]
@ruleeeer Thank you for your contribution!
Can you think of some kind of unit test the browser related part of the library to prevent regressions in the future ?

**Comment by ruleeeer** [comment]
No problem, let me provide the unit tests for the browser part, but it may take a little time

**Comment by martin-g** [comment]
The simpler, the better!
Bundles would make it harder to understand the errors.
I'd try with Puppeteer.

**Comment by ruleeeer** [comment]
I see that the project uses mocha, let me try to use mocha to do this so that I can minimize the added dependencies, or migrating to Puppeteer as you said would be a good option

**Comment by ruleeeer** [comment]
@martin-g 
Could you help me? I have a problem with test case.
When I use test frameworks (such as Mocha headless chrome or mochify) to build tests, they all use 'browserify' to bundle the test code (because Avro uses require), but if 'browserify' finds that `require ('buffer ')` is used during bundling, it will automatically mount the `Buffer` to the global attribute, as shown in the figure below. You can find this part of the document here https://github.com/browserify/browserify#compatibility
image

This means that if we use the "browserify" test library to bundle code, we will never find the problem of "Buffer is not defined". However, Avro browser uses require, we must rely on bundling to convert it into a syntax recognized by the browser. In this way, how should we build test cases? (I can't imagine how to do this without webpack or rollup)

**Comment by ruleeeer** [comment]
@martin-g 
When upgrading from webpack4 to webpack5, the `Buffer is not defined` issue will definitely occur when using Avro-browser, because webpack4 has `browserify` built in, which will automatically convert it for you, but webpack5 has to declare `browserify` manually, like Configure it like this
``` javascript
resolve: {
    fallback: {
      'buffer':require.resolve('buffer')
    }
  }
```
But that's not enough, you'll still run into the `Buffer is not defined` problem and you'll need to add a little configuration after searching stackoverflow or searching the webpack  documentation
``` javascript
plugins: [
    new webpack.ProvidePlugin({
      Buffer: ['buffer', 'Buffer'],
    }),
  ],
```
This is where you'll find Avro working properly，But this is only `webapck`, there are also projects that use `rollup` or `vite` etc. to complete the application bundle, which will cause everyone using avro-browser to have to search for how to configure to solve the `Buffer is not defined` problem, also, in the official Nodejs documentation it is pointed out that although Buffer hangs globally, but a display declaration is a better approach.You can find it here https://nodejs.org/api/buffer.html#buffer,

image

It only takes two lines to fix the above problem, doesn't it?

**Comment by martin-g** [comment]
I see!
I think the best would be to use ESM (EcmaScript modules) but I'm not sure
how hard it would be for the existing users (both Node.js and browser ones)
to migrate.

Please use your preferred bundler for the test. I'll investigate the
migration to ESM soon!

**Comment by ruleeeer** [comment]
Although I think you probably already know this, I'm still making a record here to see how ESM is supported by browsers and nodejs,From what I've looked up, it probably has more of an impact on Nodejs, as I've seen very few issues with browsers using Avro

## Nodejs
image


## Browser
image

**Comment by ruleeeer** [comment]
Also, is my testing still necessary? (At least so far I haven't found any problems with it except for `Buffer is not defined`) because ESM's testing method may be very different from browserify

**Comment by martin-g** [comment]
If there is a chance to move to ESM then indeed there is no point in adding
more code now.

**Comment by martin-g** [comment]
Thank you for the contribution, @ruleeeer !

**Comment by martin-g** [comment]
I've created https://issues.apache.org/jira/browse/AVRO-3338 for ESM.

**Pull request merged**
