### PR TITLE
AVRO-3369: Move default reader to own file

### PR DESCRIPTION
**Pull request by KyleSchoonover**
### Jira

- [ ] My PR addresses the following [Avro Jira](https://issues.apache.org/jira/browse/AVRO/) issues and references them in the PR title. For example, "AVRO-1234: My Avro PR"
  - https://issues.apache.org/jira/browse/AVRO-3369

### Tests

- [ ] My PR does not need testing for this extremely good reason: non functional changes

### Commits

- [ ] My commits all reference Jira issues in their subject lines. In addition, my commits follow the guidelines from "[How to write a good git commit message](https://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [ ] In case of new functionality, my PR adds documentation that describes how to use it.
  - All the public functions and the classes in the PR contain Javadoc that explain what it does

### CODE REVIEW

**Review by martin-g — COMMENTED** [review]
This looks like an API break to me.
An inner class is now moved to a proper/outer class. Any users of it will have to fix the imports ?!

**Comment by KyleSchoonover** [comment]
This one wasn't actually an inner class.  It was just two classes in the same file.  The code remains in the same namespace.  So no changes are required for consumers.

**Comment by zcsizmadia** [comment]
We will lose a lot of git history if we start to split old files into multiple new ones for no real benefit. During my development many times I rely on git comments and commit messages on certain lines in the code. This change would reset the git history for these classes after they are moved to a new file.

**Comment by martin-g** [comment]
I agree with @zcsizmadia - git history will be lost for no real benefit. Closing...

**Pull request closed without merging**
