### PR TITLE
AVRO-3930: Mapping org.apache.hadoop.io.ZStandardCodec to zstandard

### PR DESCRIPTION
**Pull request by yaooqinn**
## What is the purpose of the change

Mapping org.apache.hadoop.io.ZStandardCodec to zstandard in 
HadoopCodecFactory

## Verifying this change

This change added tests 

## Documentation

- Does this pull request introduce a new feature? (yes)
- If yes, how is the feature documented? (JavaDocs)

### CODE REVIEW

**Review by martin-g — APPROVED** [review]

**Comment by martin-g** [comment]
Not related to this PR but I wonder how `CodecFactory.fromString("deflate");` works ?! 
In one of the tests it returns `DeflateCodec.class`, while in another it returns `GzipCodec.class`

**Comment by martin-g** [comment]
@KalleOlaviNiemitalo I meant these two tests:
- https://github.com/apache/avro/blob/61fd3e4c245409e60a57c45494ca461f56a834e3/lang/java/mapred/src/test/java/org/apache/avro/hadoop/file/TestHadoopCodecFactory.java#L29
- https://github.com/apache/avro/blob/61fd3e4c245409e60a57c45494ca461f56a834e3/lang/java/mapred/src/test/java/org/apache/avro/hadoop/file/TestHadoopCodecFactory.java#L50

I didn't fire an IDE to debug what is going on. It seems one is an alias to the other...

**Comment by yaooqinn** [comment]
Thanks for the review, @martin-g, and @KalleOlaviNiemitalo. 

Shall I fix the GzipCodec issue here? Or with a follow-up, as it seems orthogonal?

**Comment by martin-g** [comment]
In a separate JIRA+PR. Thank you!

**Comment by yaooqinn** [comment]
Hi, @martin-g @KalleOlaviNiemitalo. Do we have any comment I missed to address for this PR？

**Comment by martin-g** [comment]
@yaooqinn I'll leave it to the Java SDK maintainers to review and merge.

**Comment by yaooqinn** [comment]
OK. I got it. Thank you @martin-g

**Pull request merged**
