### PR TITLE
[AVRO-2318] Bump hadoop-client from 2.7.3 to 3.2.0

### PR DESCRIPTION
**Pull request by Fokko**
https://jira.apache.org/jira/browse/AVRO-2318

### CODE REVIEW

**Comment by Fokko** [comment]
Always those dates:
```
[ERROR] Failures: 
[ERROR]   TestSpecificLogicalTypes.testAbilityToReadJodaRecordWrittenAsJsr310Record:205 
Expected: is "22:14:16"
     but: was "22:14:16.000"
```

**Comment by iemejia** [comment]
I am pro the move to Hadoop 3, specially since this is a provided dependency, but I am wondering how can we ensure that we don't break backwards compatibility with Hadoop 2.x (Most hadoop distros are still in the 2.x line). Wondering what more hadoop savy people have to say on this one. @cutting ?

**Comment by scottcarey** [comment]
I think we should figure out how to decouple the hadoop stuff so we can have multiple releases simultaneously.

Otherwise, people stuck on hadoop 2 won't be able to use Avro 1.9.0 easily -- so far the incompatibilities are not that great assuming you're already using a java 8+ JVM.

Possibly, we build and release with two different classifiers, but classifiers don't also change transitive deps.

So we would need different artifactIds for each flavor, `o.a.avro:avro-mapred2:1.9.0` and `o.a.avro:avro-mapred3:1.9.0`
Something like Avro 1.9.0

**Comment by iemejia** [comment]
Agree 100% with @scottcarey I think this deserves a little bit more than just updating the version. Since the dependency is provided/optional I think we can just add an additional profile to validate that Avro's tests work with both versions of the library. I will close this ticket temporally @Fokko and hope to open a PR to tackle this later this week.

**Pull request closed without merging**
