### PR TITLE
Make 1.7 branch build

### PR DESCRIPTION
**Pull request by radai-rosenblatt**
Seems like AVRO-1681 was only partially applied to the 1.7 branch. Specifically, the expected test output was not updated to reflect changes in javadoc.
This commit fixes the tests and makes the build pass

Signed-off-by: radai-rosenblatt radai.rosenblatt@gmail.com

### CODE REVIEW

**Comment by radai-rosenblatt** [comment]
...bump?

**Comment by benmccann** [comment]
Confirmed. I ran into the same issue. The [same commit on branch-1.8](https://github.com/apache/avro/commit/b81761e72307bfc62843c0b207a4712aa2d9c9c0) edits additional files.

**Comment by spacharya** [comment]
+1 on the patch.
mvn test ran successfully.

**Comment by busbey** [comment]
Thanks for the fix @radai-rosenblatt! I've pushed it to branch-1.7. Unfortunately, github won't automatically close this until there's a commit on master.

If you have a chance to close this PR, that'd be great. Otherwise I'll do a bulk closing later.

**Comment by radai-rosenblatt** [comment]
thank you

**Pull request closed without merging**
