### PR TITLE
AVRO-3845: avro-tools: Add log entry when an external schema is used

### PR DESCRIPTION
**Pull request by rulle-io**
## What is the purpose of the change
When `avro-tools fromjson` parameter `--schema-file` or `--schema` is used, it is unclear whether the tool actually picked up the provided schema.

## Verifying this change
This change is a trivial rework / code cleanup without any test coverage.

Also a couple of code style warnings are fixed.

### CODE REVIEW

**Comment by clesaec** [comment]
Nice small change.
Please, could you create a JIRA (as explain on [how to contribute](https://avro.apache.org/project/how-to-contribute/#making-changes)), then i'll approve the change and then ping a commiter about it.

**Comment by rulle-io** [comment]
Thanks @clesaec. I have sent a request to get a Jira user (to create a ticket). But no response since a few weeks back.

**Comment by martin-g** [comment]
@rulle-io 
```
ASF Self-serve Portal - Friday, July 14, 2023 8:55:26 AM GMT+3

New Jira account created: rulle-io

Hi there,
As approved by mgrigorov@apache.org, a new Jira user account, rulle-io, has been created.

They provided the public name: Ruslan Altynnikov
and the reason: Submit a PR
```

**Comment by rulle-io** [comment]
Done: https://issues.apache.org/jira/browse/AVRO-3845 .

**Comment by rulle-io** [comment]
Tested manully:

### --schema-file
```
avro-tools fromjson --schema-file example.avro example.json
...
23/08/26 14:46:15 INFO tool.DataFileReadTool: Reading schema from file 'example.avro'
```

### --schema
```
avro-tools fromjson --schema {"namespace":"example.avro","type":"record","name":"User","fields":[{"name":"name","type":"string"},{"name":"favorite_number","type":"int"},{"name":"favorite_color","type":"string"}]} example.avro
...
23/08/26 15:04:33 INFO tool.DataFileReadTool: Reading schema from string '{namespace:example.avro,type:record,name:User,fields:[{name:name,type:string},{name:favorite_number,type:int},{name:favorite_color,type:string}]}'
```

**Review by opwvhk — APPROVED** [review]

**Review by clesaec — APPROVED** [review]
:+1:

**Pull request merged**
