### PR TITLE
AVRO-2332: Support java_multiple_files protobuf option

### PR DESCRIPTION
**Pull request by syucream**
JIRA issue: https://issues.apache.org/jira/browse/AVRO-2332

Support java_multiple_files option,
https://developers.google.com/protocol-buffers/docs/proto3#options

The option helps to get classes via reflection.

### CODE REVIEW

**Comment by iemejia** [comment]
Can you fill a JIRA for this (and rename the title of the PR accordingly), given its size and scope it seems worth an independent JIRA.

**Comment by syucream** [comment]
@iemejia I did that 👍

**Comment by syucream** [comment]
It's so important to handle protobuf well-known types, like `com.google.protobuf.Timestamp` because these use the option.
https://github.com/protocolbuffers/protobuf/blob/master/src/google/protobuf/timestamp.proto#L40

**Comment by iemejia** [comment]
We introduced automatic code formatting. For more info see the "[How to contribute](https://cwiki.apache.org/confluence/display/AVRO/How+To+Contribute)" page. This  probably affected this PR can you please rebase it.

**Comment by syucream** [comment]
I rebased it, but got the error in `JAVA=8`:
```
...
/usr/share/dotnet/sdk/2.2.105/NuGet.targets(114,5): error : Unable to load the service index for source https://api.nuget.org/v3/index.json. [/testptch/unknown/lang/csharp/src/apache/codegen/Avro.codegen.csproj]
/usr/share/dotnet/sdk/2.2.105/NuGet.targets(114,5): error :   Resource temporarily unavailable [/testptch/unknown/lang/csharp/src/apache/codegen/Avro.codegen.csproj]

Total Elapsed time:  27m  1s



-1 overall

 _____     _ _                _ 
|  ___|_ _(_) |_   _ _ __ ___| |
| |_ / _` | | | | | | '__/ _ \ |
|  _| (_| | | | |_| | | |  __/_|
|_|  \__,_|_|_|\__,_|_|  \___(_)
```
Can I fix it by just retrying CI job?

**Pull request merged**
