### PR TITLE
Update apache/commons-compress to 1.21

### PR DESCRIPTION
**Pull request by andeb**
A bunch of vulnerabilities have been disclosed recently for the version 1.20:

https://snyk.io/vuln/SNYK-JAVA-ORGAPACHECOMMONS-1316638
https://snyk.io/vuln/SNYK-JAVA-ORGAPACHECOMMONS-1316640
https://snyk.io/vuln/SNYK-JAVA-ORGAPACHECOMMONS-1316641
https://snyk.io/vuln/SNYK-JAVA-ORGAPACHECOMMONS-1316639

Make sure you have checked _all_ steps below.

### Jira

- [ ] My PR addresses the following [Avro Jira](https://issues.apache.org/jira/browse/AVRO/) issues and references them in the PR title. For example, "AVRO-1234: My Avro PR"
  - https://issues.apache.org/jira/browse/AVRO-XXX
  - In case you are adding a dependency, check if the license complies with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).

### Tests

- [ ] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

### Commits

- [ ] My commits all reference Jira issues in their subject lines. In addition, my commits follow the guidelines from "[How to write a good git commit message](https://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [ ] In case of new functionality, my PR adds documentation that describes how to use it.
  - All the public functions and the classes in the PR contain Javadoc that explain what it does

### CODE REVIEW

**Comment by andeb** [comment]
@iemejia for visibility

**Comment by RyanSkraba** [comment]
Thanks for the contribution!

**Review by RyanSkraba — APPROVED** [review]

**Comment by tomasAlabes** [comment]
Hi @RyanSkraba, any news on the mailing list? Without a release the vulnerability is still out there 😕

**Comment by RyanSkraba** [comment]
Hey!  I agree we have not moved as fast as we could on this major release.  The permalink is [here](https://lists.apache.org/thread.html/r73cf034ec47524e239dabda6fc7dcef547e9fa4d29f6aab1b353ea3d%40%3Cdev.avro.apache.org%3E) -- I'll relaunch this more aggressively after ApacheCon!

**Comment by tomasAlabes** [comment]
Thanks Ryan, it seems that there are a few items to be finished/tested before the release. Wouldn't it be faster to publish a `1.10.3` until `1.11.0` is ready? Just an idea, as probably a lot of people are getting security warnings because of this (and the fix is simple).

**Comment by cedoucette** [comment]
Yes, please, we can't release the latest version of our product until we address all of our security vulnerabilities, and this is one of them. Having a release of arvo with this fix (e.g. 1.10.3) would allow us to proceed.

**Comment by martin-g** [comment]
@cedoucette If you use Maven/Gradle/Ivy/Sbt then you can specify the version of commons-compress in your app. There is no need to upgrade Avro. 
Apart from this there was an attempt to release Avro 1.11.0 last week, but there were few regressions found. There will be a second attempt soon! Please follow the dev@ mailing list, test your app with 1.11.0 and cast your vote!

**Comment by cedoucette** [comment]
For anyone else reading this, 1.11.0 was just released. I presume (but have not yet verified) that that release (1.11.0) contains this fix.

**Comment by martin-g** [comment]
> I presume (but have not yet verified) that that release (1.11.0) contains this fix.

https://github.com/apache/avro/blob/release-1.11.0/lang/java/pom.xml#L55

**Pull request merged**
