### PR TITLE
AVRO-3427: skip creation of namespace directories for csharp schema

### PR DESCRIPTION
**Pull request by kordos**
…of directories for namespace. Just generate classes in output directory

Make sure you have checked _all_ steps below.

### Jira

- [x] My PR addresses the following [Avro Jira](https://issues.apache.org/jira/browse/AVRO-3427)

### CODE REVIEW

**Review by martin-g — APPROVED** [review]

**Comment by zcsizmadia** [comment]
https://github.com/apache/avro/pull/1574 (if approved and merged) will have manu unit tests for checking the generated directory structure. I think it would be great to extend those unit tests with this flag to make sure that the files end up in places wherw it is expected

**Comment by zcsizmadia** [comment]
Are the other langauges have this capability?

**Comment by kordos** [comment]
> 

As I'm mainly developing in C# I do not know if any other language have such capability. 
I'll dig into unit test soon. I just wanted to create early PR to get some comments ;)

**Comment by kordos** [comment]
> 

I cannot find unit tests for changed methods: Avro.AvroGen.GenSchema and Avro.CodeGen.WriteTypes. Is it unit tested anywhere?

**Comment by zcsizmadia** [comment]
Other languages  I meant the avrogen tool (e.g. avrogen for c++, ...). If they jave --skip-namespaces flag at all, or something similar, just to match the name of the argument.

**Comment by kordos** [comment]
> #1574 has a new file lang/csharp/src/apache/test/CodGen/AvroGenTests.cs, which has tests to validate avrogen as an integration test, from a very high level, by calling the tool with command line arguments, compile the schema file, compile all the generated cs files. There are test cases for the matching the generated types and the generated file names.

Do you know when it will be merged?

**Comment by zcsizmadia** [comment]
Not sure, however if this is merged sooner, I will make suer to add unit tests to cover new flag with the flattened structure

**Comment by kordos** [comment]
> Other languages I meant the avrogen tool (e.g. avrogen for c++, ...). If they jave --skip-namespaces flag at all, or something similar, just to match the name of the argument.

I checked briefly and I didn't notice any flag like `-skip-namespaces` used in C++ or java

**Comment by kordos** [comment]
> Not sure, however if this is merged sooner, I will make suer to add unit tests to cover new flag with the flattened structure

Ok, then I'm changing this draft as ready to review. if #1574 will be merged first then I'll add test. If no then unit tests will be added after #1574 will be merged.

**Comment by kordos** [comment]
@martin-g Could you merge this PR and create a new nuget package from it?

**Comment by martin-g** [comment]
I have enabled the CI checks.
I will review it later and if everything is OK I can merge it. I was hoping @zcsizmadia or @KyleSchoonover to give their blessing (PR approval) because I am not C# developer and my reviews here are not very reliable! :-)
The nuget will be released once Avro 1.11.1/1.12.0 is released. I am not sure when this will happen!

**Comment by kordos** [comment]
> I have enabled the CI checks. I will review it later and if everything is OK I can merge it. I was hoping @zcsizmadia or @KyleSchoonover to give their blessing (PR approval) because I am not C# developer and my reviews here are not very reliable! :-) The nuget will be released once Avro 1.11.1/1.12.0 is released. I am not sure when this will happen!

Thanks for your answer. Is there a scheduled release of nuget packages? I was thinking that merge to master will create nuget package and the number will be based on actual change and semantic versioning? isn't that the case?

**Comment by martin-g** [comment]
> I was thinking that merge to master will create nuget package and the number will be based on actual change and semantic versioning? isn't that the case?

No. Apache projects are more conservative. 
Releases are prepared by a release manager, once in a while.
Then they are voted for at least 3 days. Here the community is encouraged to test the proposed artifacts and report any problems.
If there is a regression then it is being fixed and the release process is restarted.
If no problems are reported then the actual release is executed and an announcement is sent to users@, dev@, ...

**Review by martin-g — APPROVED** [review]

**Comment by zcsizmadia** [comment]
Looks ok, however it is always hard to say so when there are no unit tests. It is not @kordos fault, simply we just dont have coverage for avrogen. I have #1571, which test coverage for avrogen, however it must be reviewed, since there is some code shuffling there. Latr today I will for just testing add this feature to my local branch and validate with unit testing, just to be sure this change has no no unknown side effect. So merging this is not blocked by #1571.

I am not sure how I feel about the name itself. My first reaction to the name if I would see it for the first time is, that the actual namespace to the classes are flattened as well, not just the directory structure. (Maybe `-flatten-directories`).

**Comment by zcsizmadia** [comment]
@martin-g Ran  some unit tests on the expected directory structure on my future test cases in #1571 and all looks good.

**Comment by kordos** [comment]
> I am not sure how I feel about the name itself. My first reaction to the name if I would see it for the first time is, that the actual namespace to the classes are flattened as well, not just the directory structure. (Maybe `-flatten-directories`).

I don't mind changing option name. I chose --skip-directories as it was my first idea and I just wanted to start PR process early. It's hard to find some short name that would be descriptive enough for that feature.  I'm open for suggestions ;)

**Comment by zcsizmadia** [comment]
I am just curious, what is the use case for this feature?

**Comment by kordos** [comment]
> I am just curious, what is the use case for this feature?

I described that in jira: https://issues.apache.org/jira/browse/AVRO-3427. Do you need any more info?

**Comment by zcsizmadia** [comment]
I understand the description, I was just curious what the use case is when a flat directory structure is preferred.

**Comment by zcsizmadia** [comment]
If the `namspace` field in the schema definition is `foo.bar.ap`, the directory structure will be `./foo/bar/ap` for that type as of now. Are you saying that avrogen generates a single `foo.bar.ap` directory? Could you provide an example schema definition, the generated directory structure and your expected directory structure here?

Here is my schema:
```
{"namespace": "org.apache.avro.codegentest.testdata",
  "type": "record",
  "name": "NestedLogicalTypesRecord",
  "doc" : "Test nested types with logical types in generated Java classes",
  "fields": [
    {
      "name": "nestedRecord",
      "type": {
        "namespace": "org.apache.avro.codegentest.testdata",
        "type": "record",
        "name": "NestedRecord",
        "fields": [
          {
            "name": "nullableDateField",
            "type": ["null", {"type": "int", "logicalType": "date"}]
          }
        ]
      }
    }]
}
```

avrogen will generate the following directory structure:

```
./org/apache/avro/codegentest/testdata/NestedLogicalTypesRecord.cs                ./org/apache/avro/codegentest/testdata/NestedRecord.cs
```

**Comment by zcsizmadia** [comment]
Are you referring this issue, which was fixed in v1.9.0?https://github.com/apache/avro/commit/6eda0b41796d5d039ace7720bbd8066f0b7835e5

What is the avrogen version you are using?

**Comment by kordos** [comment]
> If the `namspace` field in the schema definition is `foo.bar.ap`, the directory structure will be `./foo/bar/ap` for that type as of now. Are you saying that avrogen generates a single `foo.bar.ap` directory? Could you provide an example schema definition, the generated directory structure and your expected directory structure here?
> 
> Here is my schema:
> 
> ```
> {"namespace": "org.apache.avro.codegentest.testdata",
>   "type": "record",
>   "name": "NestedLogicalTypesRecord",
>   "doc" : "Test nested types with logical types in generated Java classes",
>   "fields": [
>     {
>       "name": "nestedRecord",
>       "type": {
>         "namespace": "org.apache.avro.codegentest.testdata",
>         "type": "record",
>         "name": "NestedRecord",
>         "fields": [
>           {
>             "name": "nullableDateField",
>             "type": ["null", {"type": "int", "logicalType": "date"}]
>           }
>         ]
>       }
>     }]
> }
> ```
> 
> avrogen will generate the following directory structure:
> 
> ```
> ./org/apache/avro/codegentest/testdata/NestedLogicalTypesRecord.cs
> ./org/apache/avro/codegentest/testdata/NestedRecord.cs
> ```

Your example is correct. It creates directory per namespace part. However in company where I'm working we are using different naming convention. Our naming convention is to use multi namespace per directory. We fallow SOA and we have hundreds, maybe even more than thousand of microservices so we won't be able to change our naming convention.
I'll use your definitions for example but we need slightly different directory structure, so in my project it should be placed in:

```
./org.apache.avro/codegentest/testdata/NestedLogicalTypesRecord.cs
./org.apache.avro/codegentest/testdata/NestedRecord.cs
```
Avrogen is not handling such cases. it will generate classes in path : /org/apache/avro/codegentest/testdata/ and not as it should be in my project: /org.apache.avro/codegentest/testdata/. Just to be clear, namespaces for generated classes are correct as there is no notion of directory. I hope it helps

**Comment by zcsizmadia** [comment]
In the future a directory mapping feature might extend avrogen to your use: `--directory-alias DIR:ALIAS`

So your execution could be: `avrogen -s example.avsc . --directories-alias org/apache/avro:org.apache.avro` the rest of the namespace sub directories would be automatically generated. Pretty much bfore creating the directory the aliases are replaced in the outputDIr in the `WriteTypes` function

**Comment by kordos** [comment]
> Thanks for the use! that makes sense. However the patch you submitted will flatten the directory and there wont be any `../codegentest/testdata/...` sub-directories. Your above example is acombinatio of sub directories + some sub directory structure is replaced by one songle directory with dotted names. How would you be using the avrogen with patches submitted to generate the files in the above example? `avrogen -s example.avsc org.apache.avro/codegentest/testdata --skip-directories` might work, however if you have many namespaces, the avrogen commands will be custom for individual schema files.

I could use it in two ways:
`avrogen -s org.apache.avro/codegentest/testdata/example.avsc org.apache.avro/codegentest/testdata --skip-directories`
or go to the end directory and run:
```
cd org.apache.avro/codegentest/testdata
avrogen -s example.avsc . --skip-directories
```
Then no matter which naming convention you're using in your project, it will always generate classes in correct directory.

Also it can be easily integrated with custom tool which I'm also thinking to build: 
1. Get directory as and input
2. get all .avsc files
3. generate classes for each schema
Such tool would be very helpfull as avrogen can handle only 1 file so when you have many files then it gets quite annoying.

**Comment by kordos** [comment]
> Are you referring this issue, which was fixed in v1.9.0?[6eda0b4](https://github.com/apache/avro/commit/6eda0b41796d5d039ace7720bbd8066f0b7835e5)
> 
> What is the avrogen version you are using?

Latest one: 1.11.0

**Comment by KyleSchoonover** [comment]
Sorry a bit behind.  I'm not big a setting a boolean for a negative action.  I would prefer the boolean be createDirectories, than an option to skip creating the directories.  Obviously be default we want to create directories.  Your command line would be to set to turn it off.

**Comment by KyleSchoonover** [comment]
@kordos @zcsizmadia If we only send parameters that have no additional information ie: `--skip-directories` over `--create-directories false`  Then I'm fine,  However, I could see a lot of parameters to make this more flexible where it would send additional configuration.  ie: `--ouput-directory <path>`

**Comment by zcsizmadia** [comment]
The issue with the command line parsing is that it uses a very basic way of doing that, without usinga  modern command line parsing library

**Comment by kordos** [comment]
> Sorry a bit behind. I'm not big a setting a boolean for a negative action. I would prefer the boolean be createDirectories, than an option to skip creating the directories. Obviously by default we want to create directories. Your command line would be to set to turn it off.

I added it as another optional parameter to not introduce breaking change in avrogen tool and because of that I would prefer to stay with this parameter as something optional for special use case.

**Comment by kordos** [comment]
> In the future a directory mapping feature might extend avrogen to your use: `--directory-alias DIR:ALIAS`
> 
> So your execution could be: `avrogen -s example.avsc . --directory-alias org/apache/avro:org.apache.avro` the rest of the namespace sub directories would be automatically generated. Pretty much bfore creating the directory the aliases are replaced in the outputDIr in the `WriteTypes` function

I like your idea with `--directory-alias` parameter as it is more flexible and I think it would be nice to introduce that in future.
 However as it is a bit more complex solution to develop and use in command line I'd like to stay with my simple option that allow to completely skip creation of directories.

**Comment by zcsizmadia** [comment]
It can be.  Indirectly unit tested it locally, seems to be ok. and the change btw is very trivial.

**Comment by KyleSchoonover** [comment]
@kordos and @zcsizmadia through together what I was thinking: https://github.com/apache/avro/pull/1594

**Comment by kordos** [comment]
> Hey there -- I haven't been following the C# PRs very closely, but I just proposed to start thinking about 1.11.1 on [the mailing list](https://lists.apache.org/thread/jbxzoq091ozy7gp7vb93m8ztlgjct7fq) Should this PR be on the radar?

Would be great if you could squeeze this change to 1.11.1 release :)

**Comment by kordos** [comment]
> @kordos and @zcsizmadia threw together what I was thinking: #1594

Ok, I know what you meant. Idea with two parts parameter is nice however parsing it looks quite complex and it would require good unit test coverage to prove that all that changes work. if we could use some library for parsing command line arguments then it would be a lot simpler.

**Comment by zcsizmadia** [comment]
@kordos #1595 is merged. Please let me know if you need any help with implementing the unit tests, however it should be fairly trivial,

**Comment by kordos** [comment]
> @kordos #1595 is merged. Please let me know if you need any help with implementing the unit tests, however it should be fairly trivial,

awesome. I'll have a look in my spare time :)

**Comment by KyleSchoonover** [comment]
@kordos Can you deal with the merge conflicts?  We are ready to merge.

**Comment by zcsizmadia** [comment]
Unit tests should be added before merge

**Comment by kordos** [comment]
> @kordos Can you deal with the merge conflicts? We are ready to merge.

Hi. Lately I didn't have time to work on this. I hope I'll find time soon and I'll add unit tests. I'll let you know if I have any issues with merge.

**Comment by kordos** [comment]
> Unit tests should be added before merge

Merge is done. I'll try to find some time to add unit tests ;)

**Comment by kordos** [comment]
@zcsizmadia, @KyleSchoonover  I added unit tests. Could you review them?

**Review by zcsizmadia — APPROVED** [review]

**Comment by zcsizmadia** [comment]
@martin-g looks ok, but test build did not run yet.

**Review by KyleSchoonover — APPROVED** [review]

**Comment by martin-g** [comment]
Thank you, @kordos !

**Pull request merged**
