### PR TITLE
AVRO-3731:[gradl- avro-plugin] Integrates software donation of gradle avro plugin

### PR DESCRIPTION
**Pull request by RanbirK**
## What is the purpose of the change

- Updates workflow files to start fixing builds after integrating software donation of gradle avro plugin

## Verifying this change

This change is already covered by existing tests, such as:
- Avro Compatibility Tests
- Gradle Compatibility Tests
- Java Compatibility Tests
- OS Compatibility Tests
- CI Build Test

## Documentation

- Does this pull request introduce a new feature? no

### CODE REVIEW

**Review by davidmc24 — APPROVED** [review]

**Review by martin-g — APPROVED** [review]

**Comment by frevib** [comment]
@martin-g could you indicate when this plugin in going to be released? The original project is not maintained any more: https://github.com/davidmc24/gradle-avro-plugin

**Comment by martin-g** [comment]
There are no indications that it will be released at all.
No one is working on this integration since several months.

**Comment by frevib** [comment]
This is really a shame to hear. @davidmc24 donated his project, was wilfully accepted, and now it might be killed? Your work is appreciated of course, but how could this have happened? What can we do to fix it? Many rely on the Gradle plugin.

**Comment by frevib** [comment]
Are those tasks listed specifically somewhere? Here there are two subtasks: https://issues.apache.org/jira/browse/AVRO-3731

@olahungerford has been working on those. I won't mind spending some time on it, if I can get some help with the idea of how everything works.

**Pull request merged**
