### PR TITLE
ci: Fix the CI builds after Github Actions moving ubuntu-latest to 24.04

### PR DESCRIPTION
**Pull request by martin-g**
Drop more pypy3.9 usages

## What is the purpose of the change

*(For example: This pull request improves file read performance by buffering data, fixing AVRO-XXXX.)*

## Verifying this change

*(Please pick one of the following options)*

This change is a trivial rework / code cleanup without any test coverage.

*(or)*

This change is already covered by existing tests, such as *(please describe tests)*.

*(or)*

This change added tests and can be verified as follows:

*(example:)*
- *Extended interop tests to verify consistent valid schema names between SDKs*
- *Added test that validates that Java throws an AvroRuntimeException on invalid binary data*
- *Manually verified the change by building the website and checking the new redirect*

## Documentation

- Does this pull request introduce a new feature? (yes / no)
- If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)

### CODE REVIEW

**Comment by martin-g** [comment]
@KalleOlaviNiemitalo @zcsizmadia Any ideas how to fix this for ubuntu-24.04:
```
Testhost process for source(s) '/home/runner/work/avro/avro/lang/csharp/src/apache/codec/Avro.File.XZ.Test/bin/Release/netcoreapp3.1/Avro.File.XZ.Test.dll' exited with error: Process terminated. Couldn't find a valid ICU package installed on the system. Set the configuration flag System.Globalization.Invariant to true if you want to run with no globalization support.
2024-10-16T07:40:09.5324651Z    at System.Environment.FailFast(System.String)
2024-10-16T07:40:09.5325787Z    at System.Globalization.GlobalizationMode.GetGlobalizationInvariantMode()
2024-10-16T07:40:09.5327122Z    at System.Globalization.GlobalizationMode..cctor()
2024-10-16T07:40:09.5328235Z    at System.Globalization.CultureData.CreateCultureWithInvariantData()
2024-10-16T07:40:09.5329310Z    at System.Globalization.CultureData.get_Invariant()
2024-10-16T07:40:09.5330141Z    at System.Globalization.CultureInfo..cctor()
2024-10-16T07:40:09.5330853Z    at System.String.ToUpperInvariant()
2024-10-16T07:40:09.5331693Z    at System.Diagnostics.Tracing.EventSource.GetGuid(System.Type)
2024-10-16T07:40:09.5333184Z    at System.Diagnostics.Tracing.EventSource..ctor(System.Diagnostics.Tracing.EventSourceSettings, System.String[])
2024-10-16T07:40:09.5334978Z    at System.Diagnostics.Tracing.EventSource..ctor()
2024-10-16T07:40:09.5336461Z    at Microsoft.VisualStudio.TestPlatform.CoreUtilities.Tracing.TestPlatformEventSource..ctor()
2024-10-16T07:40:09.5338503Z    at Microsoft.VisualStudio.TestPlatform.CoreUtilities.Tracing.TestPlatformEventSource..cctor()
2024-10-16T07:40:09.5340327Z    at Microsoft.VisualStudio.TestPlatform.CoreUtilities.Tracing.TestPlatformEventSource.get_Instance()
2024-10-16T07:40:09.5341999Z    at Microsoft.VisualStudio.TestPlatform.TestHost.Program.Main(System.String[])
```
?

**Review by kojiromike — APPROVED** [review]

**Comment by zcsizmadia** [comment]
Sorry for being late to the convo. As @KalleOlaviNiemitalo said the isse is the libucu. I wasn't aware that  3.1 cannot run at all on ubuntu 24.04 since it is so old. The only reason all the EOL net targets I still kept in the supported frameworks was to be paranoid when it comes to testing.were. It is totally safe to remove the netcoreapp3.1 support (or any of the others which are not getting supported on newer OSs).

**Comment by kojiromike** [comment]
For doc/ref:

There are a slew issues referenced at https://github.com/actions/runner-images/issues/10636

GitHub's runner image for ubuntu-24.04 is just plain broken for Python as of now. (As opposed to just backwards-incompatible to how we were doing things).

**Comment by zcsizmadia** [comment]
Just checked netcoreapp5.0, and even the plain compiler it is not working on a plain ubuntu 24.04. SO 3.1 and 5.0 should be removed (which is ok), to be able to run on ubuntu 24.04 runner.

**Comment by martin-g** [comment]
As you may noticed I set `ubuntu-22.04` for the C# workflows to make it work again.
Feel free to open a new PR for dropping the old .NET versions.

For Python I used `python3 -m pip install --break-system-packages ...` because the CI uses short-lived VMs anyway and one should not bother with polluting the system namespace. Again feel free to improve if you see a better way!

**Comment by zcsizmadia** [comment]
I will have a PR soon.

**Comment by zcsizmadia** [comment]
#3214

**Comment by kojiromike** [comment]
> For Python I used python3 -m pip install --break-system-packages ... because the CI uses short-lived VMs anyway and one should not bother with polluting the system namespace. Again feel free to improve if you see a better way!

This is fine for actions, IMO.

**Pull request merged**
