### PR TITLE
AVRO-3062: Upgrade javascript mocha and handlebars transitive dependencies

### PR DESCRIPTION
**Pull request by iemejia**
I am not 100% clear about how the lock file works but it seems to be the way to override the unwanted deps.

R: @RyanSkraba

### CODE REVIEW

**Review by RyanSkraba — APPROVED** [review]
I'm not sure of the impact of moving to lockfileVersion 2 in package-lock.json, but npm implies that it's backwards compatible with npm 6!

**Comment by iemejia** [comment]
Yes I am not sure what is best because using npm 6.x seems not to be able to fix the security updates, if you run `npm audit` you get the changes on the first commit, but if you run `npm audit` it still fails. However if you apply the updates proposed by npm 7 and re run `npm audit` with both npm 6.x and npm 7.x you get no vulnerabilities reported.
Maybe we should bet on the backwards compatibility and go ahead. Tell me what you think and if you agree I will squash the commits to make the cherry picking easier. (I let them separate just to show you the weird case).

**Comment by RyanSkraba** [comment]
Hmmm -- I can reproduce and test the changes.

I tried building the result with npm 6.x (node:10 like the docker) and npm 7.x (node:15) using the `lockVersion: 2` from your PR and the results of the avro-js tar file were identical (except for a missing `/etc/deprecated/README` file in the latter, which I'm going to assume is no big deal!)

There are nine tests that fail with `npm run cover` using node:15, but they also fail on master, so I'm assuming that's not directly related to these bumps.  I raised https://issues.apache.org/jira/browse/AVRO-3063 to note that.

My node.js experience is pretty limited, but AFAIK, this looks fine to merge (and cherry pick to 1.10.2)

**Comment by iemejia** [comment]
Thanks Ryan. Hopefully there won't be regressions and we will get rid of the security messages. :crossed_fingers:

**Pull request merged**
