### PR TITLE
AVRO-2399: Use Wheels for Python Distribution

### PR DESCRIPTION
**Pull request by kojiromike**
We want to use Python wheels to distribute the Avro Python package.
[Here's some motivation](https://pythonwheels.com/).

### Jira

- [x] My PR addresses [AVRO-2399](https://issues.apache.org/jira/browse/AVRO-2399)
- [x] My PR title references it.
- [x] My PR adds a test-time dependency in [tox-wheel](https://github.com/ionelmc/tox-wheel), which is licensed under the BSD-2-clause, which complies with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).

### Tests

- [x] My PR adds no tests, but tests the python code using the wheel distribution instead of the tarball (sdist) one.

### Commits

- [x] My commits all reference Jira issues in their subject lines.
- [x] In addition, my commits follow the guidelines from "[How to write a good git commit message](https://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [x] My PR contains updates to documentation appropriate for making better use of modern Python install tooling.

### CODE REVIEW

**Comment by edgarrmondragon** [comment]
This was merged but wheels have never been published for the Python distribution. I can confirm  this https://github.com/apache/avro/blob/0d00709770ed16d695c19f8129380fe9a5246a23/lang/py/build.sh#L38-L52

does produce a valid distribution, tested with the (adapted to Python 3) code sample in https://avro.apache.org/docs/1.11.1/getting-started-python/#serializing-and-deserializing-without-code-generation.

**Comment by martin-g** [comment]
I think I see the problem!

https://cwiki.apache.org/confluence/display/AVRO/How+To+Release#HowToRelease-Publishing says this for Python:

```
Publish Python artifacts to PyPI. To do this you'll need an [account on PyPi](https://docs.python.org/2/distutils/packageindex.html), and write access to the [Avro package](https://pypi.python.org/pypi/avro) - ask the existing owners for permission if you don't have it. 

# To install twine in the docker image
export PATH=~/.local/bin/:$PATH
python3 -m pip install --user --upgrade twine pip

mkdir -p tmp/py
cd tmp/py
tar xvfz ../../dist/py/avro-X.Y.X.tar.gz
cd avro-X.Y.Z
python setup.py sdist
twine upload dist/*
```

It needs `python setup.py sdist_wheel` too.

**Comment by kojiromike** [comment]
Hmm, we should probably shift to using [`build`](https://packaging.python.org/en/latest/key_projects/#build) anyway. That will build the sdist and the wheel, efficiently, in a sandboxed manner. But yeah, `sdist_wheel` is a good step in the right direction, too.

**Comment by kojiromike** [comment]
@edgarrmondragon thanks for letting us know. I did not realize the wheels were not getting published.

**Comment by edgarrmondragon** [comment]
Thank you @kojiromike for your quick response! Does this in the short term it's a matter of, in the short term, amending [the guide](https://cwiki.apache.org/confluence/display/AVRO/How+To+Release#HowToRelease-Publishing) so the release manager doesn't need to change their workflow, and in the long term updating the workflow to use `build`/`tox`?

**Comment by kojiromike** [comment]
I already amended the guide. I will email the list and see if we can get a wheel published.

**Pull request merged**
