### PR TITLE
AVRO-3609: [Rust] Add support for custom attributes

### PR DESCRIPTION
**Pull request by martin-g**
### Jira

- [X] https://issues.apache.org/jira/browse/AVRO-3609

### Tests

- [X] My PR adds unit tests

### Commits

- [X] My commits all reference Jira issues in their subject lines. In addition, my commits follow the guidelines from "[How to write a good git commit message](https://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [X] Adds rustdoc

### CODE REVIEW

**Comment by martin-g** [comment]
@untereiner Please take a look and tell what you think!

**Comment by untereiner** [comment]
I am a rust beginner so I can not comment the code but for what I know it seems good. 
I find it very good to output serde_json::Value types instead of strings like in the c++ version.

> Do we want to support serializing the custom attributes?
this is what is ambiguous in the spec for me.

I understand this: 
> where typeName is either a primitive or derived type name, as defined below. Attributes not defined in this document are permitted as metadata, but must not affect the format of serialized data

as not serializing to not modify the format of serialized data

**Comment by martin-g** [comment]
Is there anything missing in the current implementation ?
I need use cases to decide what should be done next.
At the moment the implementation can read custom attributes at top-level and record field level.

**Comment by untereiner** [comment]
My use case is to read custom attributes at the top-level of a schema.
So I guess nothing is missing in the current implementation

**Comment by martin-g** [comment]
Thanks for the review, @untereiner !

**Comment by untereiner** [comment]
I guess I have to wait until next release to use it directly from crates.io ?

**Comment by martin-g** [comment]
Yes! 
But you could try it now by pointing to a local checkout or git:// . I'd be thankful if you test it now so we can fix any problems before making a proper release.

**Pull request merged**
