### PR TITLE
chore: Fix ci for icelake-dev

### PR DESCRIPTION
**Pull request by liurenjie1024**
## What is the purpose of the change

*(For example: This pull request improves file read performance by buffering data, fixing AVRO-XXXX.)*

## Verifying this change

*(Please pick one of the following options)*

This change is a trivial rework / code cleanup without any test coverage.

*(or)*

This change is already covered by existing tests, such as *(please describe tests)*.

*(or)*

This change added tests and can be verified as follows:

*(example:)*
- *Extended interop tests to verify consistent valid schema names between SDKs*
- *Added test that validates that Java throws an AvroRuntimeException on invalid binary data*
- *Manually verified the change by building the website and checking the new redirect*

## Documentation

- Does this pull request introduce a new feature? (yes / no)
- If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)

### CODE REVIEW

**Comment by liurenjie1024** [comment]
cc @ZENOTME

**Review by ZENOTME — APPROVED** [review]
Thanks!

**Comment by liurenjie1024** [comment]
Sorry for the noise, we put it to wrong repo.

**Comment by martin-g** [comment]
Don't worry! I wouldn't accept it anyway without a JIRA issue and a proper PR description! 😄 
I'm glad you find the CI configs useful!

**Pull request closed without merging**
