### PR TITLE
remove unnecessary import from generated Java classes

### PR DESCRIPTION
**Pull request by naferx**
`org.apache.avro.generic.GenericArray` is not used anywhere in this file

## What is the purpose of the change

*(For example: This pull request improves file read performance by buffering data, fixing AVRO-XXXX.)*

## Verifying this change

*(Please pick one of the following options)*

This change is a trivial rework / code cleanup without any test coverage.

*(or)*

This change is already covered by existing tests, such as *(please describe tests)*.

*(or)*

This change added tests and can be verified as follows:

*(example:)*
- *Extended interop tests to verify consistent valid schema names between SDKs*
- *Added test that validates that Java throws an AvroRuntimeException on invalid binary data*
- *Manually verified the change by building the website and checking the new redirect*

## Documentation

- Does this pull request introduce a new feature? (yes / no)
- If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)

### CODE REVIEW

**Comment by naferx** [comment]
> > `org.apache.avro.generic.GenericArray` is not used anywhere in this file
> 
> Can references to GenericArray be output by any method called from this file?
> 
> I suspect they cannot, because java.util.List<elementType> is used instead:
> 
> https://github.com/apache/avro/blob/fd1433954f8344ffa433a42734e0dce1cd71deea/lang/java/compiler/src/main/java/org/apache/avro/compiler/specific/SpecificCompiler.java#L836-L837

I am not entirely sure because, just getting familiarized with the code base. In a generated class I double-checked any existing references to that class. None found

**Comment by naferx** [comment]
pinging @KalleOlaviNiemitalo, just to follow up this PR

**Comment by nielsbasjes** [comment]
I did a quick double check of the codebase.

The mentioned `schema.getElementType()` returns something which is a `Schema` and `GenericArray` is not a `Schema` (it is a `List` and a `GenericContainer`).
So that specific line will not be a reason to keep it.

However looking at [the commit that introduced it](https://github.com/apache/avro/commit/b4ede4b116b24b5308e8419504a73e02b7f7e406) I do see this for example: https://github.com/apache/avro/blob/d143d6262f7d6c688e695d1656f8609605835604/lang/java/compiler/src/main/velocity/org/apache/avro/compiler/specific/templates/java/classic/record.vm#L668-L673

I'm not 100% sure but to me it seems possible this can happen if someone creates a (custom) logical type that uses this as the underlying javaType.

If this is correct I do not want this change, I would rather have a demonstration that shows a usecase as part of the tests.

@Fokko @opwvhk @martin-g WDYT?

**Review by opwvhk — APPROVED** [review]
> The mentioned `schema.getElementType()` returns something which is a `Schema` and `GenericArray` is not a `Schema` [...] So that specific line will not be a reason to keep it.

This line of reasoning is wrong, as the method `javaType` takes the schema and returns the actual type.

However, the conclusion is correct: the returned type is a fully qualified name. This means there is no import needed unless the static code in the template uses it (which is not the case).

**Comment by nielsbasjes** [comment]
Ok, thanks for the check. This change is good then.

**Pull request merged**
