### PR TITLE
AVRO-2439: Remove a DeprecationWarning from Py3 test

### PR DESCRIPTION
**Pull request by sekikn**
Make sure you have checked _all_ steps below.

### Jira

- [x] My PR addresses the following [Avro Jira](https://issues.apache.org/jira/browse/AVRO/) issues and references them in the PR title. For example, "AVRO-1234: My Avro PR"
  - https://issues.apache.org/jira/browse/AVRO-2439
  - In case you are adding a dependency, check if the license complies with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).

### Tests

- [x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

No additional test since it's a fix for the test itself. I ran `./build.sh test` in the lang/py3 directory and confirmed all of the tests passed.

### Commits

- [x] My commits all reference Jira issues in their subject lines. In addition, my commits follow the guidelines from "[How to write a good git commit message](https://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [x] In case of new functionality, my PR adds documentation that describes how to use it.
  - All the public functions and the classes in the PR contain Javadoc that explain what it does

### CODE REVIEW

**Comment by kojiromike** [comment]
The test failure seems due to a flake-out in Travis, rather than a problem with this PR per se.

**Comment by Fokko** [comment]
Restarted Travis

**Comment by nandorKollar** [comment]
Indeed, I think Travis has some problems, for several other PRs the tests failed with messages like "Could not transfer artifact xyz from/to central (https://repo.maven.apache.org/maven2): Access denied to: https://repo.maven.apache.org/maven2/org/xzy"

Despite this is probably a transient issue, shouldn't we wait with merging new PRs until this is resolved? Merging PRs with failing CI pollutes the commit log with a lot of commits which have failed build, and actually CI couldn't verify that the change didn't break anything.

**Comment by Fokko** [comment]
Yes I fully agree with you @nandorKollar. After restarting the CI, it became green again: https://travis-ci.org/apache/avro/builds/548532671

Threfore the status is now green as well. It would be better to fix the underlying issue, but not sure how to solve this.

**Pull request merged**
