### PR TITLE
AVRO-3841: Try exact schema match first in union type

### PR DESCRIPTION
**Pull request by zcsizmadia**
Make sure you have checked _all_ steps below.

### Jira

- [x] My PR addresses the following [Avro Jira](https://issues.apache.org/jira/browse/AVRO/) issues and references them in the PR title. For example, "AVRO-1234: My Avro PR"
  - https://issues.apache.org/jira/browse/AVRO-XXX
  - In case you are adding a dependency, check if the license complies with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).

### Tests

- [x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

### Commits

- [x] My commits all reference Jira issues in their subject lines. In addition, my commits follow the guidelines from "[How to write a good git commit message](https://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [x] In case of new functionality, my PR adds documentation that describes how to use it.
  - All the public functions and the classes in the PR contain Javadoc that explain what it does

### CODE REVIEW

**Comment by zcsizmadia** [comment]
Previous comment in MatchingBranch indicated, that the exact type match was removed because of perfromance. That particular code is the initial implementation, created by https://issues.apache.org/jira/browse/AVRO-533. However Avro.perf did not show significant performance degradation after the patch.

**Comment by KyleSchoonover** [comment]
@zcsizmadia Can you show the perf results?  Other than that, I agree with the change.

**Comment by zcsizmadia** [comment]
Before (single run):
```
type    impl                    action          total_items     batches         batch_size      time(ms)
simple  default_specific        serialize       1000000         1000            1000            468
simple  default_specific        deserialize     1000000         1000            1000            860
simple  preresolved_specific    serialize       1000000         1000            1000            312
simple  preresolved_specific    deserialize     1000000         1000            1000            313
simple  default_generic         serialize       1000000         1000            1000            390
simple  default_generic         deserialize     1000000         1000            1000            766
simple  preresolved_generic     serialize       1000000         1000            1000            250
simple  preresolved_generic     deserialize     1000000         1000            1000            484
complex default_specific        serialize       1000000         1000            1000            3000
complex default_specific        deserialize     1000000         1000            1000            6031
complex preresolved_specific    serialize       1000000         1000            1000            2375
complex preresolved_specific    deserialize     1000000         1000            1000            3266
complex default_generic         serialize       1000000         1000            1000            2719
complex default_generic         deserialize     1000000         1000            1000            4125
complex preresolved_generic     serialize       1000000         1000            1000            1922
complex preresolved_generic     deserialize     1000000         1000            1000            2546
narrow  default_specific        serialize       1000000         1000            1000            188
narrow  default_specific        deserialize     1000000         1000            1000            359
narrow  preresolved_specific    serialize       1000000         1000            1000            141
narrow  preresolved_specific    deserialize     1000000         1000            1000            172
narrow  default_generic         serialize       1000000         1000            1000            187
narrow  default_generic         deserialize     1000000         1000            1000            344
narrow  preresolved_generic     serialize       1000000         1000            1000            125
narrow  preresolved_generic     deserialize     1000000         1000            1000            219
wide    default_specific        serialize       1000000         1000            1000            2438
wide    default_specific        deserialize     1000000         1000            1000            4562
wide    preresolved_specific    serialize       1000000         1000            1000            1797
wide    preresolved_specific    deserialize     1000000         1000            1000            1891
wide    default_generic         serialize       1000000         1000            1000            1953
wide    default_generic         deserialize     1000000         1000            1000            4734
wide    preresolved_generic     serialize       1000000         1000            1000            1391
wide    preresolved_generic     deserialize     1000000         1000            1000            2875
```

After (single run):
```
type    impl                    action          total_items     batches         batch_size      time(ms)
simple  default_specific        serialize       1000000         1000            1000            484
simple  default_specific        deserialize     1000000         1000            1000            860
simple  preresolved_specific    serialize       1000000         1000            1000            328
simple  preresolved_specific    deserialize     1000000         1000            1000            328
simple  default_generic         serialize       1000000         1000            1000            406
simple  default_generic         deserialize     1000000         1000            1000            797
simple  preresolved_generic     serialize       1000000         1000            1000            250
simple  preresolved_generic     deserialize     1000000         1000            1000            500
complex default_specific        serialize       1000000         1000            1000            2953
complex default_specific        deserialize     1000000         1000            1000            5937
complex preresolved_specific    serialize       1000000         1000            1000            2360
complex preresolved_specific    deserialize     1000000         1000            1000            3422
complex default_generic         serialize       1000000         1000            1000            2828
complex default_generic         deserialize     1000000         1000            1000            3984
complex preresolved_generic     serialize       1000000         1000            1000            1922
complex preresolved_generic     deserialize     1000000         1000            1000            2563
narrow  default_specific        serialize       1000000         1000            1000            218
narrow  default_specific        deserialize     1000000         1000            1000            344
narrow  preresolved_specific    serialize       1000000         1000            1000            141
narrow  preresolved_specific    deserialize     1000000         1000            1000            156
narrow  default_generic         serialize       1000000         1000            1000            219
narrow  default_generic         deserialize     1000000         1000            1000            375
narrow  preresolved_generic     serialize       1000000         1000            1000            125
narrow  preresolved_generic     deserialize     1000000         1000            1000            218
wide    default_specific        serialize       1000000         1000            1000            2500
wide    default_specific        deserialize     1000000         1000            1000            4579
wide    preresolved_specific    serialize       1000000         1000            1000            1796
wide    preresolved_specific    deserialize     1000000         1000            1000            1969
wide    default_generic         serialize       1000000         1000            1000            1985
wide    default_generic         deserialize     1000000         1000            1000            4250
wide    preresolved_generic     serialize       1000000         1000            1000            1328
wide    preresolved_generic     deserialize     1000000         1000            1000            2625
```

**Review by KyleSchoonover — APPROVED** [review]
The perf appears negligible.  Looks good to make the change.

**Comment by martin-g** [comment]
Thank you, @zcsizmadia !

**Pull request merged**
