### PR TITLE
AVRO-4014: [Rust] Add value and schema to ValidationWithReason error class

### PR DESCRIPTION
**Pull request by CodingAnarchy**
## What is the purpose of the change

This pull request is intended to improve the logging of value-schema mismatch errors when appending data to a `Writer`, so that it specifies which value and schema failed validation. This changes the current error: `Value does not match schema: Reason: Unsupported value-schema combination` to specify `Value {value} does not match schema {schema}`, bringing it in line with other error reporting in some of the other structs in the Rust implementation of Avro.

This aims to make it easier to debug the issue underlying AVRO-4014 and determine what is causing it.

## Verifying this change

This change is a trivial rework / code cleanup without any test coverage.

## Documentation

- Does this pull request introduce a new feature? (yes / no)
- If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)

### CODE REVIEW

**Comment by martin-g** [comment]
Please see https://github.com/apache/avro/blob/bb5b8429b7bec86a972f2f1f5ae5f18eeef332a7/lang/rust/avro/src/types.rs#L381-L392

**Comment by CodingAnarchy** [comment]
@martin-g Unfortunately, that log doesn't get fired because `src/writer.rs` uses `Value#validate_internal` itself in the code that is raising the error I see:

https://github.com/apache/avro/blob/bb5b8429b7bec86a972f2f1f5ae5f18eeef332a7/lang/rust/avro/src/writer.rs#L538-L577

Is the preference instead that I update this code in the writer to use the same logging format as in `Value#validate_schemata`?

**Comment by martin-g** [comment]
@CodingAnarchy Please review https://github.com/apache/avro/pull/3007/commits/a6fbfe2744a335a7c6cae44ea6f4486c63a18921

**Comment by CodingAnarchy** [comment]
@martin-g All makes sense to me. Thanks for your help cleaning it up!

**Comment by martin-g** [comment]
Thank you for the contribution, @CodingAnarchy!

**Pull request merged**
