### PR TITLE
AVRO-2745: Generate optional getters for nullables only

### PR DESCRIPTION
**Pull request by kaliy**
Make sure you have checked _all_ steps below.

### Jira

- [x] My PR addresses the following [Avro Jira](https://issues.apache.org/jira/browse/AVRO/) issues and references them in the PR title. For example, "AVRO-1234: My Avro PR"
  - https://issues.apache.org/jira/browse/AVRO-2745
  - In case you are adding a dependency, check if the license complies with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).

### Tests

- [x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

### Commits

- [x] My commits all reference Jira issues in their subject lines. In addition, my commits follow the guidelines from "[How to write a good git commit message](https://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [x] In case of new functionality, my PR adds documentation that describes how to use it.
  - All the public functions and the classes in the PR contain Javadoc that explain what it does

### CODE REVIEW

**Comment by Bluexin** [comment]
Hey, it looks like the build failed because of a connection issue.
Any update on this? We'd like to use this feature without having to hardcode it in velocity templates :)

**Comment by RyanSkraba** [comment]
Retriggered Java 8 and Windows builds on Travis.

**Comment by Bluexin** [comment]
The windows build is failing because of some dependency issues, which doesn't seem to be caused by this PR.

**Comment by kaliy** [comment]
hi, the pull request has been approved. could you please merge it?
and what about 1.9? should I backport this change to that branch as well?

**Comment by Fokko** [comment]
Thanks @kaliy for the contribution. This will be in 1.10 which will be released soon.

**Pull request merged**
