### PR TITLE
AVRO-3405: Add API to write/read user metadata in .avro file

### PR DESCRIPTION
**Pull request by martin-g**
### Jira

- [X] My PR addresses the following [Avro Jira](https://issues.apache.org/jira/browse/AVRO/) issues and references them in the PR title. For example, "AVRO-1234: My Avro PR"
  - https://issues.apache.org/jira/browse/AVRO-3405

### Tests

- [X] My PR adds new unit tests

### Commits

- [X] My commits all reference Jira issues in their subject lines. In addition, my commits follow the guidelines from "[How to write a good git commit message](https://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [X] In case of new functionality, my PR adds documentation that describes how to use it.
  - All the public functions and the classes in the PR contain Rustdoc that explain what it does

### CODE REVIEW

**Review by kvc-code — CHANGES_REQUESTED** [review]
Thank you for getting to this so quickly!
After reading through the PR I went ahead and cloned the repo to test against this new Branch. Unfortunately it is not working as expected.
(1) the Key and Value that user specifies in the API call should be literally inserted as additional Key and Value in the Avro metadata. This implementation adds a fixed Key "avro.user_metadata" with a Value that is a serialized Map. This will not work for us and is unlike any other API we have used (avrow and fastavro). Basic requirement is that we define both the Key and the Value. We understand that Keys prefixed with "avro." are reserved so it would be Ok if you error out on such a Key.

(2) Per the Spec and as implemented by `avrow` the Value is Bytes and not String. We are Ok with String since that is all we ever use but we think it would be best to align with the Spec and not limit the caller of this API to String even if that is the more common use case. Someone, somewhere may have used some Value that is not UTF-8 String (not us) and they should be supportable per the Spec.

(3) We prefer the approach taken by `avrow` where `.set_metadata()` is a Builder method and therefore does not require we declare the Writer as `mut`. This is a minor issue, however.

**Comment by martin-g** [comment]
All done!
Please review!

> We prefer the approach taken by `avrow` where `.set_metadata()` is a Builder method and therefore does not require we declare the Writer as `mut`

I've added support for this. But I don't see how useful an immutable Writer could be - you cannot add records/datum to it.

**Review by kvc-code — APPROVED** [review]
This branch works for me now. I tested reading and writing user metadata in the forms we have been doing with other libraries and it works. Thank you!

**Comment by martin-g** [comment]
Thanks for the help, @kvc-code !

**Pull request merged**
