### PR TITLE
AVRO-2662: Report Coverage in Python Tests

### PR DESCRIPTION
**Pull request by kojiromike**
### Jira

- [x] My PR addresses [AVRO-2662](https://issues.apache.org/jira/browse/AVRO-2662)
- [x] My PR references it in the PR title.
- [x] My PR adds a test-time dependency in [coveragepy](https://github.com/nedbat/coveragepy/). It is licensed under the Apache-2.0 license, which complies with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).

### Tests

- [x] My PR only adds build tooling.

### Commits

- [x] My commits all reference Jira issues in their subject lines.
- [x] My commits follow the guidelines from "[How to write a good git commit message](https://chris.beams.io/posts/git-commit/)".

### Documentation

- [x] My PR only adds build tooling.

### CODE REVIEW

**Comment by kojiromike** [comment]
You can e see the results of this change in Travis CI by searching for `coverage report`

```
Name                                   Stmts   Miss  Cover
----------------------------------------------------------
avro/__init__.py                           2      0   100%
avro/constants.py                          9      0   100%
avro/datafile.py                         227     18    92%
avro/io.py                               603     93    85%
avro/ipc.py                              293     60    80%
avro/protocol.py                         150     28    81%
avro/schema.py                           545     46    92%
avro/test/__init__.py                      0      0   100%
avro/test/av_bench.py                     41     41     0%
avro/test/gen_interop_data.py             30      4    87%
avro/test/mock_tether_parent.py           46     32    30%
avro/test/sample_http_client.py           35     35     0%
avro/test/sample_http_server.py           31     31     0%
avro/test/test_datafile.py               139      5    96%
avro/test/test_datafile_interop.py        32      1    97%
avro/test/test_io.py                     185      1    99%
avro/test/test_ipc.py                     14      1    93%
avro/test/test_protocol.py                78      9    88%
avro/test/test_schema.py                 190      5    97%
avro/test/test_script.py                 148      2    99%
avro/test/test_tether_task.py             54      3    94%
avro/test/test_tether_task_runner.py      83      5    94%
avro/test/test_tether_word_count.py       78      7    91%
avro/test/txsample_http_client.py         46     46     0%
avro/test/txsample_http_server.py         21     21     0%
avro/test/word_count_task.py              22      0   100%
avro/tether/__init__.py                    4      0   100%
avro/tether/tether_task.py               175     52    70%
avro/tether/tether_task_runner.py        106     32    70%
avro/tether/util.py                        8      0   100%
avro/timezones.py                         18      3    83%
avro/tool.py                             113    113     0%
avro/txipc.py                            133    133     0%
----------------------------------------------------------
TOTAL                                   3659    827    77%
___________________________________ summary ____________________________________
```

**Comment by Fokko** [comment]
Nice work @kojiromike. It would be cool if we could also push this to coveralls, so we can have a badge on the README.md.

**Comment by kojiromike** [comment]
@Fokko can you show me how to do that? I created this INFRA ticket to learn about such things: https://issues.apache.org/jira/browse/INFRA-19615

**Comment by Fokko** [comment]
So for Airflow we have Codecov: https://codecov.io/github/apache/airflow?branch=master

It seems like we can just configure this, but I think we still need Infra to add some secrets to Travis.
https://issues.apache.org/jira/browse/INFRA-16672?jql=project%20%3D%20INFRA%20AND%20text%20~%20codecov

**Comment by kojiromike** [comment]
@Fokko If you wouldn't mind creating an AVRO ticket for this, I'd be happy to take a look sometime in the next couple of weeks. (But I really want to merge my python3 PR first, and that needs some review.)

**Comment by Fokko** [comment]
Happy to help @kojiromike. I've created the ticket: https://issues.apache.org/jira/browse/INFRA-19669

**Pull request merged**
