### PR TITLE
AVRO-3218: Fix parsing of logicalType = decimal

### PR DESCRIPTION
**Pull request by vegraux**
Make sure you have checked _all_ steps below.

### Jira

- [x] My PR addresses the following [AVRO-3218](https://issues.apache.org/jira/browse/AVRO-3218) issue 

### Tests

- [x] My PR adds to the following unit tests: [`lang/py/avro/test/test_schema.TestMisc.test_decimal_valid_type`](https://github.com/vegraux/avro/commit/4ad20199420a40846898462e52c1fe82ccbd84be#diff-d5bd2c903fbc9d00b21cd566f5af8da89bc757ecefbf6df2a3006b84492ae124R655):

### Commits

- [x] My commits all reference Jira issues in their subject lines. In addition, my commits follow the guidelines from "[How to write a good git commit message](https://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [x] In case of new functionality, my PR adds documentation that describes how to use it.
  - All the public functions and the classes in the PR contain Javadoc that explain what it does

### CODE REVIEW

**Review by martin-g — APPROVED** [review]

**Comment by vegraux** [comment]
@martin-g I fixed the lint-issue and amended to the same commit

**Review by martin-g — APPROVED** [review]

**Comment by vegraux** [comment]
@RyanSkraba Is there a place I can check to see what is planned to be included in future releases? Would really appreciate to get this in 1.11.1, it is a really annoying bug

**Comment by martin-g** [comment]
The way to schedule something for a specific release is to set the "Fix Version" in the JIRA ticket.
This way the ticket will be reviewed before the release. If everything is clear and the PR is approved then it will be resolved. Otherwise the Fix Version will be edited.
In both cases the release manager will take your ticket into account when the release time comes.
Depending on how many tickets are fixed and what kind of changes are applied with them it might be versioned as 1.11.1 or 1.12.0.

**Comment by kojiromike** [comment]
I don't think we have a policy that says that merging a PR has to wait for a specific release. The actual release process uses different branches. So I'm happy to merge this now, and then if the ticket says this bugfix needs to go into 1.11.1 then it can.

**Comment by cccs-eric** [comment]
@martin-g I just ran into this issue and wanted to contribute a fix when I discovered that `master` already contains a fix!  Would it be possible to know when `1.11.1` will be released?  This is a blocker for me....

**Comment by martin-g** [comment]
There is a mail thread about this at dev@ mailing list.
I hope it will be released soon!

**Comment by vegraux** [comment]
@RyanSkraba When is the next release (`1.11.1`) planned? I must manually build avro with the bugfix, and push to my company's artifactory to get around this. It often causes dependency problems

**Comment by vegraux** [comment]
> There is a mail thread about this at dev@ mailing list. I hope it will be released soon!

Do you have an update on the release @martin-g?

**Comment by martin-g** [comment]
https://lists.apache.org/thread/jbxzoq091ozy7gp7vb93m8ztlgjct7fq

**Pull request merged**
