### PR TITLE
AVRO-2697: Cherry-pick python changes into branch-1.9

### PR DESCRIPTION
**Pull request by kojiromike**
### Jira

- [x] This PR addresses [AVRO-2697](https://issues.apache.org/jira/browse/AVRO-2697)
- [x] This PR references that ticket in its title.

### Tests

- [x] This PR is made of cherry-picks, so consists of whatever tests are part of the same changes against master.

### Commits

- [x] The commits reference the Jira issues they reference in the same commits against master.

### Documentation

- [x] This PR is made of cherry-picks, so consists of whatever documentation is part of the same changes against master.

### CODE REVIEW

**Comment by Fokko** [comment]
Thanks @kojiromike. I've updated the tickets to target them at 1.9.2

**Comment by RyanSkraba** [comment]
I've just added all of the commits cherry-picked and identified from AVRO-2697 -- pushed the intermediate work, but I'm still doing some checks on the python changes and the related JIRA.

**Comment by RyanSkraba** [comment]
OK!  I've done some validation -- I'm fairly confident that the commits I cherry-picked are OK for an eventual 1.9.2 release (and if I missed some commits hopefully we'll find them in the release candidates).  I'll clean up the `fixup!` commits and rebase.

**Comment by kojiromike** [comment]
Thanks, Ryan and Fokko,

In the future I'll be more careful about picking what changes I think should go into the release branch. Chalk this one up to learning about the avro release process.

**Comment by RyanSkraba** [comment]
*N.B.* This last batch of commits was just a manual `rebase --interactive --autosquash` to clean up the history.  There should be strictly no code changes in the cherry-picks, just merging the `fixup!` commits back into them correctly.

**Pull request merged**
