### PR TITLE
Fix avro-c build failing on new cmake and MacOs

### PR DESCRIPTION
**Pull request by gaborbernat**

### CODE REVIEW

**Comment by gaborbernat** [comment]
@thiru-mg ping on this?

**Comment by gaborbernat** [comment]
Guess it's not happening.

**Comment by olivierlacan** [comment]
@gaborbernat For you and the bug archaeologists like me, the variables were fixed in https://github.com/apache/avro/commit/4e03a4c21d120b55acf16340ba122c6878ffdc6c so Avro version 1.12.0 should have this fixed. 

Do you think the Snappy issue is still a blocker?

**Comment by gaborbernat** [comment]
Been so long now can't remember anymore.

**Pull request closed without merging**
