### PR TITLE
[AVRO-2145] Cannot create Javadoc on JDK8+

### PR DESCRIPTION
**Pull request by Fokko**
From Java 8 on the JavaDoc is being linted and it will fail early if there are issues with the JavaDoc: http://openjdk.java.net/jeps/172

This patch will add the missing Javadoc with some stubs. Additionally I updated the docs of some of the public API by hand to make the Javadoc more verbose.

The JavaDoc needs to be updated in the future, but this commit will let the compiler pass the javadoc check step.

Tested locally and it passes the tests. This patch only changes the Javadoc and does not change the logic of the code.

Cheers, Fokko

### CODE REVIEW

**Comment by kojiromike** [comment]
@cutting I'm happy to help review stuff when I can, but 157 files is a bit much for manual review. Can I help here by confirming I have run the tests locally?

**Comment by kojiromike** [comment]
I can confirm this passes all the java-related tests.

**Comment by cutting** [comment]
I'm not fond of whitespace changes.  Are all of these really required to pass JavaDoc lint?  In particular, a lot of existing Javadoc comments have content on the first line.  When these are moved to a new line it causes the rest of the comment to be re-indented.  I'd prefer we don't make that style change here.

**Comment by nandorKollar** [comment]
In this case I'd recommend simply turning off DocLint. I remember we did similar things on Parquet, [here's](https://github.com/apache/parquet-format/commit/28ead3fd157842247ac71c5ec1fac94f1ff83ec4) how it was turned off there.

**Comment by Fokko** [comment]
Currently it breaks the `dist` step. 

Personally I would prefer to add the JavaDoc. But if the majority prefers to turn it off, I'm fine with it as well. Beside the missing JavaDoc, I've also corrected a lot of the invalid JavaDoc in this PR.

**Comment by nandorKollar** [comment]
I think in some cases it would make sense to fix the Javadoc, but adding obvious comments only for DocLint doesn't give too much value. For example (at least in my opinion) we should keep changes like [this](https://github.com/apache/avro/pull/334/files#diff-8c641f2365208209cae8dd63a6d186f7L35), but changes only related to the comment style like [this](https://github.com/apache/avro/pull/334/files#diff-6e7994042bf667704678c9395ace00bcL103) don't give too much value.

**Comment by Fokko** [comment]
Ok, I'll create a new PR.

**Pull request closed without merging**
