### PR TITLE
Add ruby decimal logical type

### PR DESCRIPTION
**Pull request by hudsonsferreira**
Make sure you have checked _all_ steps below.

### Jira

- [ ] My PR addresses the following [Avro Jira](https://issues.apache.org/jira/browse/AVRO/) issues and references them in the PR title. For example, "AVRO-1234: My Avro PR"
  - https://issues.apache.org/jira/browse/AVRO-XXX
  - In case you are adding a dependency, check if the license complies with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).

### Tests

- [X] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

### Commits

- [ ] My commits all reference Jira issues in their subject lines. In addition, my commits follow the guidelines from "[How to write a good git commit message](https://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [ ] In case of new functionality, my PR adds documentation that describes how to use it.
  - All the public functions and the classes in the PR contain Javadoc that explain what it does

### CODE REVIEW

**Comment by Fokko** [comment]
Thanks for the contribution @hudsonsferreira 

It looks like we have a lint error:
```
test/test_logical_types.rb:38:5: W: Lint/UselessAssignment: Useless assignment to variable - schema.
    schema = Avro::Schema.parse <<-SCHEMA
    ^^^^^^
```

**Comment by hudsonsferreira** [comment]
> Thanks for the contribution @hudsonsferreira
> 
> It looks like we have a lint error:

Hi @Fokko thanks for the review. Fixed it.

**Comment by ziggythehamster** [comment]
> I believe that the encoded representation of the decimal should be the unscaled value, not a string representation.

Even worse, you have to produce a special sequence of bytes (which in Ruby is a string, but don't let that fool you into thinking `"1.234"` is correct). It must conform to this specification:

> A decimal logical type annotates Avro bytes or fixed types. The byte array must contain the two's-complement representation of the unscaled integer value in big-endian byte order. The scale is fixed, and is specified using an attribute.

https://avro.apache.org/docs/current/spec.html#Decimal

**Comment by tjwp** [comment]
Encoding/decoding added in #1102

**Pull request closed without merging**
