### PR TITLE
AVRO-2639: add option to write Optional only when fields are nullable

### PR DESCRIPTION
**Pull request by ecopoesis**
Make sure you have checked _all_ steps below.

### Jira

- [x] My PR addresses the following issues and references them in the PR title. For example, "AVRO-1234: My Avro PR"
  - [AVRO-2639](https://issues.apache.org/jira/browse/AVRO-2639)
  - In case you are adding a dependency, check if the license complies with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).

### Tests

- [x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

- `testPojoWithOptionalOnlyWhenNullableCreatedTurnedOn`
- `testPojoWithOptionalOnlyWhenNullableCreatedTurnedOnAndGettersReturnOptionalTurnedOff`

### Commits

- [x] My commits all reference Jira issues in their subject lines. In addition, my commits follow the guidelines from "[How to write a good git commit message](https://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [x] In case of new functionality, my PR adds documentation that describes how to use it.
  - All the public functions and the classes in the PR contain Javadoc that explain what it does

### CODE REVIEW

**Comment by kan-izh** [comment]
Nice! While you are here, I think it is a good idea to tweak it further: Use OptionalInt/OptionalLong/OptionalDouble for corresponding primitive types.

**Comment by Bluexin** [comment]
This looks like it implements the same functionality as #817, but that implementation's velocity template seemed a bit cleaner at first glance.
Regardless, is there something blocking this or the other PR? I don't mind helping out.

**Comment by daicode-jan** [comment]
Would be nice to have an update on this important feature

**Comment by Fokko** [comment]
Thanks for the PR, I like this one. Would be much nicer if we could use the primitive types, as @kan-izh suggests.

**Pull request closed without merging**
