### PR TITLE
AVRO-3512: Fix the aliases' namespace when parsing named schemata

### PR DESCRIPTION
**Pull request by martin-g**
### Jira

- [X] My PR addresses the following [Avro Jira](https://issues.apache.org/jira/browse/AVRO/) issues and references them in the PR title. For example, "AVRO-1234: My Avro PR"
  - https://issues.apache.org/jira/browse/AVRO-3512

### Tests

- [X] My PR adds new unit tests

### Commits

- [X] My commits all reference Jira issues in their subject lines. In addition, my commits follow the guidelines from "[How to write a good git commit message](https://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [X] A typo is fixed in the documentation.

### CODE REVIEW

**Comment by martin-g** [comment]
// CC @jklamer @radai-rosenblatt

**Comment by radai-rosenblatt** [comment]
looks OK to me and my lack of familiarity with rust :-)

my only concern is i still dont know if aliases into the null namespace are a bug or a feature. 
personally i definitely think they should be a feature (and i have used them at work before), but there's been no response on my issue yet

**Review by jklamer — APPROVED** [review]
LGTM. I'm wondering if the aliases are all fully qualified names then we should store them in a 'Name' struct? Not sure upsides or downsides though

**Comment by martin-g** [comment]
> I'm wondering if the aliases are all fully qualified names then we should store them in a 'Name' struct? Not sure upsides or downsides though

I like the idea! Let's try it and see!

**Comment by martin-g** [comment]
I will extract the "Alias is a Name" to a separate issue/PR. It is a bigger change that is not really related to this issue/PR.

**Comment by martin-g** [comment]
I am going to merge this PR even without the confirmation of the current Java behavior in the JIRA ticket.
I will adapt it later if the Java impl changes!

**Pull request merged**
