### PR TITLE
AVRO-2531: Update commons-compress to version 1.19

### PR DESCRIPTION
**Pull request by iemejia**
R: @Fokko or @dkulp 

https://issues.apache.org/jira/browse/AVRO-2531

### CODE REVIEW

**Comment by iemejia** [comment]
All green now so merging.

**Comment by iemejia** [comment]
@Fokko I let you cherry pick it since I did not understand where to do it, because we have now two 1.9 branches (`branch-1.9` and `branch-1.9.1`. What is the goal of `branch-1.9.1` or this was just a mistake? probably worth to use only branch-1.9` for consistency with old releases, maybe something to fix for RC3.

**Comment by Fokko** [comment]
No problem. I've cherry-picked it onto both branches. The `branch-1.9` is already there for Avro 1.9.2.

**Comment by iemejia** [comment]
Thanks ! Maybe we should then remove `branch-1.9.1` to avoid confusion and update the RC2 (+ RC3) towards the `branch-1.9` one.

**Comment by Fokko** [comment]
Yes, in my mind having another branch was more convenient than in practice. I'll remove the `branch-1.9.1` after the release. RC3 is inbound.

**Pull request merged**
