### PR TITLE
Corrected typo in method name (getConversion)

### PR DESCRIPTION
**Pull request by fversaci**
changed
   `getConverion(String fieldName)`
into
  `getConversion(String fieldName)`

### CODE REVIEW

**Comment by fversaci** [comment]
Sure, I was just browsing the code and wanted to notify of the typo. Please handle it the way you think is better.

**Comment by gszadovszky** [comment]
My suggestions might be misleading a bit. I've meant to suggest you creating a JIRA about the issue. I'm not a committer either so I won't be able to commit your PL anyway.
Sorry for the inconvenience. :)

**Comment by fversaci** [comment]
Ok, I'll create the JIRA right away, including your suggestions.

**Comment by gszadovszky** [comment]
Thanks a lot, @fversaci!

**Comment by fversaci** [comment]
Here it is: https://issues.apache.org/jira/browse/AVRO-1972

**Comment by rdblue** [comment]
I agree with @gszadovszky about adding the correct method and deprecating the old one, with a note that it will be removed in 1.9.0. I don't think anyone will have used this, so it should be fine.

**Comment by dkulp** [comment]
This has already been handled.  It's marked deprecated in 1.8.2 and is removed in 1.9

**Pull request closed without merging**
