### PR TITLE
AVRO-3669: [python] Add py.typed marker file (PEP561 compliance)

### PR DESCRIPTION
**Pull request by kaisen**
## What is the purpose of the change

* This pull request adds a py.typed marker file so the package will advertise itself as supporting type checking according to PEP561.

## Verifying this change

This change is already covered by existing tests. There is no new functionality.

I manually verified that `./build.sh dist` creates an sdist that contains the new `py.typed` file.

## Documentation

- Does this pull request introduce a new feature? no
- If yes, how is the feature documented? not applicable

### CODE REVIEW

**Review by martin-g — APPROVED** [review]

**Comment by martin-g** [comment]
There are some failing tests with Python 3.10.
They are not related to this PR but it would be nice if you can help us fixing them too!

**Comment by martin-g** [comment]
The issue with Python 3.10 could be fixed in a separate PR (https://issues.apache.org/jira/browse/AVRO-3667)

**Comment by palfrey** [comment]
Any thoughts on when this is likely to get into a new release?

**Comment by faph** [comment]
We would love seeing this being released too!

**Pull request merged**
