### PR TITLE
AVRO-2717: Fix undefined behavior in ZigZag encoding (< c++20)

### PR DESCRIPTION
**Pull request by oandrew**
Make sure you have checked _all_ steps below.

### Jira

- [x] My PR addresses the following [Avro Jira](https://issues.apache.org/jira/browse/AVRO/) issues and references them in the PR title.
  - https://issues.apache.org/jira/browse/AVRO-2717
### Tests

- [x] My PR does not need testing for this extremely good reason:
  -  code already covered

### Commits

- [x] My commits all reference Jira issues in their subject lines. In addition, my commits follow the guidelines from "[How to write a good git commit message](https://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [x] In case of new functionality, my PR adds documentation that describes how to use it.
  - All the public functions and the classes in the PR contain Javadoc that explain what it does

### CODE REVIEW

**Comment by mkmkme** [comment]
@martin-g This is a very simple yet important PR. I don't seem to be able to approve these changes, but this LGTM. Could this be merged?

**Comment by martin-g** [comment]
Now the diff looks different than before resolving the conflict!
Still good ?

**Comment by martin-g** [comment]
I broke it.
Let me check out and fix it!

**Comment by martin-g** [comment]
I'm afraid more work is needed here.
https://github.com/apache/avro/blob/main/lang/c%2B%2B/api/Zigzag.hh#L32-L42 has similar code that does not use `static_cast<int64_t>`

@mkmkme Could you please open a new PR with all needed changes ? Thanks!

**Comment by martin-g** [comment]
Superseded by https://github.com/apache/avro/pull/2744

**Pull request closed without merging**
