### PR TITLE
AVRO-2911: Return .NET 4.5.2 support

### PR DESCRIPTION
**Pull request by antrv**
Make sure you have checked _all_ steps below.

### Jira

- [X] My PR addresses the following [AVRO-2911](https://issues.apache.org/jira/browse/AVRO-2911) issue and reference them in the PR title. 
  - https://issues.apache.org/jira/browse/AVRO-2911
  - In case you are adding a dependency, check if the license complies with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).

### Tests

- [X] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:
- No new functionality added or no functionality changed

### Commits

- [X] My commits all reference Jira issues in their subject lines. In addition, my commits follow the guidelines from "[How to write a good git commit message](https://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [X] In case of new functionality, my PR adds documentation that describes how to use it.
  - No new functionality

### CODE REVIEW

**Comment by mhowlett** [comment]
fwiw lgtm

**Review by KyleSchoonover — COMMENTED** [review]
With .Net 4.5.2 reaching end of support on April 22nd, 2002 I believe it is safe to close this MR out.

**Comment by KyleSchoonover** [comment]
@martin-g This can be closed out.  .Net 4.5.2 will reach end of support on April 22nd, 2022

**Comment by martin-g** [comment]
Closing as suggested by @KyleSchoonover .

**Pull request closed without merging**
