### PR TITLE
AVRO-1901: Record named Exception generated bad code

### PR DESCRIPTION
**Pull request by radai-rosenblatt**
NOTE - I did not update CHANGES.txt

### CODE REVIEW

**Comment by benmccann** [comment]
@gszadovszky would you be able to merge this since you LGTM'd it?

**Comment by gszadovszky** [comment]
I wish I could, @benmccann. I am not a committer.

**Comment by benmccann** [comment]
@radai-rosenblatt this code appears to already be present on branch-1.8

**Comment by radai-rosenblatt** [comment]
yup, looks like it was picked up. closing this PR. thanks @benmccann

**Comment by benmccann** [comment]
NP. I submitted a PR to backport to 1.7: https://github.com/apache/avro/pull/188

**Pull request closed without merging**
