### PR TITLE
Add singingbush changes

### PR DESCRIPTION
**Pull request by RanbirK**
## What is the purpose of the change

*(For example: This pull request improves file read performance by buffering data, fixing AVRO-XXXX.)*

## Verifying this change

*(Please pick one of the following options)*

This change is a trivial rework / code cleanup without any test coverage.

*(or)*

This change is already covered by existing tests, such as *(please describe tests)*.

*(or)*

This change added tests and can be verified as follows:

*(example:)*
- *Extended interop tests to verify consistent valid schema names between SDKs*
- *Added test that validates that Java throws an AvroRuntimeException on invalid binary data*
- *Manually verified the change by building the website and checking the new redirect*

## Documentation

- Does this pull request introduce a new feature? (yes / no)
- If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)

### CODE REVIEW

**Comment by RanbirK** [comment]
> This pull request contains the same commits as #2310, followed by hundreds of commits rebased from the "main" branch. Specifically, the 521 commits [3bc92f3](https://github.com/apache/avro/commit/3bc92f3ee7b1894e1b50f57d74779d88d02d7bcc)..[fccd6eb](https://github.com/apache/avro/commit/fccd6eb57b0bb1e5c8606d0eada3ceec64da7bad) in this pull request have been rebased from the 521 commits [50e2db1](https://github.com/apache/avro/commit/50e2db18ebaf9d9e74e5fd92afb6027221cefe83)..[f99ed98](https://github.com/apache/avro/commit/f99ed98f12407528c0b3c5e461875c6a54525cdc) on the "main" branch.
> 
> ```
> $ git ls-remote https://github.com/apache/avro refs/pull/{2310,2906}/{head,merge}
> 3bc92f3ee7b1894e1b50f57d74779d88d02d7bcc        refs/pull/2310/head
> e4914d3429ba87bf1bf04b0072be40424658b1c7        refs/pull/2310/merge
> fccd6eb57b0bb1e5c8606d0eada3ceec64da7bad        refs/pull/2906/head
> fd612d88c6876c889e70cfbb16d056b65809dd00        refs/pull/2906/merge
> ```
> 
> At the moment, both pull requests would result in the same tree if merged: https://github.com/apache/avro/compare/refs/pull/2310/merge..refs/pull/2906/merge
> 
> ```
> $ git rev-parse refs/pull/2310/merge^{tree} refs/pull/2906/merge^{tree}
> d08186dcbf28a841f6b6774f0f03077c091dd34c
> d08186dcbf28a841f6b6774f0f03077c091dd34c
> ```
> 
> This pull request doesn't seem to have any advantages over #2310, but the rebased commits make this pull request harder to review.
Given that https://github.com/davidmc24/gradle-avro-plugin was archived in Oct 2023 and the other PR is open for almost a year and not much progress was happening on that we wanted to take it up to resolve the issues to expedite the availability of  this avro gradle plugin. Please let me know if we need to approach volunteering differently.

**Comment by martin-g** [comment]
Here are hints:

1. You need to explain your ideas better next time by using properly the title and the description fields of the PR!
By ignoring them you ask to be ignored. 

2. You might ask someone to help you with Git!
A fresh new PR is expected to have a few commits, not hundreds.

**Comment by martin-g** [comment]
IMO any new work on this/these task(s) should be done against a temporary branch.
We could not merge to `main` branch PRs which do not pass the CI checks.
https://github.com/apache/avro/pull/2310 introduces 130 new CI checks - this is almost 10 times more than what we have now for **all** SDKs! This setup should be re-considered !
Once this temporary branch is stable enough we could merge it to `main`.

**Comment by martin-g** [comment]
See https://github.com/apache/avro/pull/2310#issuecomment-2120010461

**Pull request closed without merging**
