### PR TITLE
[AVRO-2768] Use a zip file friendly way to open VERSION.txt

### PR DESCRIPTION
**Pull request by calleo**
Make sure you have checked _all_ steps below.

### Jira

- [X] My PR addresses the following [Avro Jira](https://issues.apache.org/jira/browse/AVRO-2768) issues and references them in the PR title. For example, "AVRO-1234: My Avro PR"
  - https://issues.apache.org/jira/browse/AVRO-2768
  - In case you are adding a dependency, check if the license complies with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).

### Tests

- [X] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

### Commits

- [X] My commits all reference Jira issues in their subject lines. In addition, my commits follow the guidelines from "[How to write a good git commit message](https://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [X] In case of new functionality, my PR adds documentation that describes how to use it.
  - All the public functions and the classes in the PR contain Javadoc that explain what it does

### CODE REVIEW

**Comment by Fokko** [comment]
Would it be possible to test this in some way?

**Comment by calleo** [comment]
Hi @Fokko!

It definitely is 😉 One way would be to build the package, bundle it in a zip file and run a short python script that tries to import the package. That would have catched the problem I had.

Came up with this rough script:
 
```#!/bin/bash

set -ex

# Test that avro package is importable when bundled in a zip file

## Setup
./build.sh dist
rm -rf ./tmp_zip_test
mkdir ./tmp_zip_test
zip -r ./tmp_zip_test/avro-package.zip ./avro


## Test

# Use a temporary dir since python will place the current dir
# in it's path and avro won't be imported from the zip file

cd ./tmp_zip_test
export PYTHONPATH="./avro-package.zip"
echo "import avro;print(avro.VERSION)" | python3
cd ..

## Teardown

rm -rf tmp_zip_test
./build.sh clean```

Porting this to python should not be a big deal and might fit the current build process better.

Another approach would be to execute to complete test-suite from the zip file, but I think that will require more changes since the tests are reading files, which won't work when everything is in the zip file. However, it would guarantee that the package is also usable (as opposed to just importable) from a zip bundle.

Let me know what you think and I'll address it in this PR.

**Comment by Fokko** [comment]
@calleo Can you rebase onto master?

**Comment by dkulp** [comment]
This was done as part of dca808f1294056cd804af4f7bd417bc1917fe8a

**Comment by calleo** [comment]
Forgot all about this one, thanks for fixing it! 🎉

**Pull request closed without merging**
