### PR TITLE
AVRO-3250: Support .NET 6.0

### PR DESCRIPTION
**Pull request by zcsizmadia**
Make sure you have checked _all_ steps below.

### Jira

- [x] My PR addresses the following [Avro Jira](https://issues.apache.org/jira/browse/AVRO-3250) issues
  - https://issues.apache.org/jira/browse/AVRO-3250
  - In case you are adding a dependency, check if the license complies with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).

### Tests

- [x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

### Commits

- [x] My commits all reference Jira issues in their subject lines. In addition, my commits follow the guidelines from "[How to write a good git commit message](https://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [x] In case of new functionality, my PR adds documentation that describes how to use it.
  - All the public functions and the classes in the PR contain Javadoc that explain what it does

### CODE REVIEW

**Review by martin-g — APPROVED** [review]

**Comment by martin-g** [comment]
It seems GitHub Actions does not yet provide v6

**Comment by zcsizmadia** [comment]
I am not sure how the gitflow test will use the latest dotnet 6.0. I dont see any reference to specify to install any of the dotnet sdks into the gitflow. I am not sure what I am missing

**Comment by zcsizmadia** [comment]
Maybe we should have setup-dotnet added to the dotnet gitflow tests (https://github.com/actions/setup-dotnet)

**Comment by zcsizmadia** [comment]
Added the .NET SDK dependencies to the github actions. (suggested by https://blog.elmah.io/building-and-testing-on-multiple-net-versions-with-github-actions/). This seems more solid, to explicitly installing it, so we dont depend on SDKS included in the latest github ubuntu image. (Which I thought was a bare image anyway)

**Comment by martin-g** [comment]
No, it is not a bare image.
See the table at https://github.com/actions/virtual-environments/#available-environments.
At the moment it is build 20211108.1

**Comment by zcsizmadia** [comment]
https://github.com/actions/virtual-environments/issues/4424#issuecomment-962938487

This suggests, that it is probably a  good idea to install the .NET SDKs explicitly and relying on the base image.

**Comment by ostsmolynets** [comment]
Hi, we are moving our projects to .net 6 and depend on Avro.Tools in some of them.
It's great to see you guys already working on the support for the new version.
Would be really nice to know if the support is coming any time soon?

**Review by martin-g — APPROVED** [review]

**Comment by martin-g** [comment]
Thank you for the contribution, @zcsizmadia !

**Comment by zcsizmadia** [comment]
@martin-g Do you have an estimate when 1.11.1 would be released? We are using avrogen and would like to move to net6, but avrogen is holding us back.

**Comment by martin-g** [comment]
There are some new C# PRs which we have to review and merge.
I guess we could start a new release later next week.

**Pull request merged**
