### PR TITLE
AVRO-3314: Updated exception thrown by IConvertable.ToType

### PR DESCRIPTION
**Pull request by KyleSchoonover**
Make sure you have checked _all_ steps below.

### Jira

- [x] My PR addresses the following [[Avro Jira](https://issues.apache.org/jira/browse/AVRO/](https://issues.apache.org/jira/browse/AVRO-3314)) issues and references them in the PR title. 
  - https://issues.apache.org/jira/browse/AVRO-3314

### Tests

- [x] My PR does not need testing for this extremely good reason: This is a throw exception change.  Not a logic change.

### Commits

- [x] My commits all reference Jira issues in their subject lines. In addition, my commits follow the guidelines from "[How to write a good git commit message](https://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [x] In case of new functionality, my PR adds documentation that describes how to use it.
  - Documentation updated in code

### CODE REVIEW

**Review by martin-g — APPROVED** [review]
LGTM!

**Review by RyanSkraba — APPROVED** [review]
Hello!  This LGTM -- a quick question, are we beautifying the C# code like we do with Java and spotless?  I can't seem to find any reference in our documentation.

**Comment by KyleSchoonover** [comment]
> 

That is an excellent question.  I'm starting small with just following some .NET (C#) coding standards.  There are a lot of updates I want to do, but starting slow.  If there are any conversation about styling or which standards we definitely want to adhere to, I would love to be involved.

**Comment by martin-g** [comment]
> There are a lot of updates I want to do, but starting slow.

Thank you for offering your help, @KyleSchoonover !
There are several open [PRs](https://github.com/apache/avro/pulls?q=is%3Aopen+is%3Apr+label%3AC%23) for which we would love to get some reviews from C# developers!

**Pull request merged**
