### PR TITLE
AVRO-2944: Fix read pointer in java reader to avoid hang on partial read input stream

### PR DESCRIPTION
**Pull request by MickJermsurawong**
Make sure you have checked _all_ steps below.

### Jira

- [x] My PR addresses the https://issues.apache.org/jira/browse/AVRO-2944

### Tests

- [x] My PR adds the following one unit test to first illustrate failure

### Commits

- [x] My commits all reference Jira issues in their subject lines. In addition, my commits follow the guidelines from "[How to write a good git commit message](https://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [x] In case of new functionality, my PR adds documentation that describes how to use it.
  - All the public functions and the classes in the PR contain Javadoc that explain what it does

### CODE REVIEW

**Comment by MickJermsurawong** [comment]
The CI failure seems unrelated to the change in this PR. 
For java 8:
```
Trevni Specification ............................... FAILURE [  3.264 s]
```
For java 11:
```
Updating dependencies
Your requirements could not be resolved to an installable set of packages.
  Problem 1
    - beberlei/composer-monorepo-plugin[v0.12, ..., v0.12.1] require composer-plugin-api ^1.0 -> found composer-plugin-api[2.0.0] but it does not match the constraint.
    - Root composer.json requires beberlei/composer-monorepo-plugin ^0.12 -> satisfiable by beberlei/composer-monorepo-plugin[v0.12, v0.12.1].
```

**Review by RyanSkraba — APPROVED** [review]
LGTM!  Good catch, and nice unit test, thanks for the contribution!

**Comment by mickjermsurawong-stripe** [comment]
Hi @RyanSkraba just wondering if this patch could be back-ported to older versions too? We are using Iceberg that still uses Avro 1.9, and Hadoop with Avro 1.7.

**Comment by RyanSkraba** [comment]
Hello!  I got caught up taking a look at the build failure -- it's obviously nothing to do with your PR, but I would have liked to see it green.

There isn't an official 1.7.x release or even 1.9.3 planned as far as I know.   We'd have to bring it up on the mailing list!

**Comment by Fokko** [comment]
@MickJermsurawong can you rebase, the CI has been fixed on master?

**Comment by MickJermsurawong** [comment]
Ah thank you Fokko for the note. Ryan, it's green now. Thank you for the review!
Will send out a note to dev list to see if folks have run into this problem.

**Comment by RyanSkraba** [comment]
Cherry-picked to [branch-1.10](https://github.com/apache/avro/commit/56b47fcde6f5d636b3ebaf4a7e238f327b06e66b)! Thanks again for this fix!

**Comment by noslowerdna** [comment]
@MickJermsurawong / @RyanSkraba I [asked a question](https://issues.apache.org/jira/browse/AVRO-2944?focusedCommentId=17276713&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-17276713) on the JIRA, curious if this fix could be improved to cover the `read` returning -1 unexpectedly as the issue description indicates it ought to.

**Pull request merged**
