### PR TITLE
AVRO-3004 Drop support for Python 3.5

### PR DESCRIPTION
**Pull request by subhashb**
This PR removes 3.5 support from build and setup, including classifiers

Closes: AVRO-3004 (https://issues.apache.org/jira/browse/AVRO-3004)

Make sure you have checked _all_ steps below.

### Jira

- [x] My PR addresses the issue "AVRO-3004 Drop support for Python 3.5"
  - https://issues.apache.org/jira/browse/AVRO-3004

### Tests

- [x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

### Commits

- [x] My commits all reference Jira issues in their subject lines. In addition, my commits follow the guidelines from "[How to write a good git commit message](https://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [x] In case of new functionality, my PR adds documentation that describes how to use it.
**NA**

### CODE REVIEW

**Review by kojiromike — COMMENTED** [review]
Can we add 3.9 now? I think it will just work.

Also, we might need to remove 3.5 and add 3.9 to the GitHub actions matrix

**Comment by subhashb** [comment]
> Can we add 3.9 now? I think it will just work.
> 
> Also, we might need to remove 3.5 and add 3.9 to the GitHub actions matrix

Done and tests pass.
Actually, Github actions were not testing for 3.5 and in turn had pypy3.7 tests. I have added pypy3.7 to tox envs.

**Review by kojiromike — APPROVED** [review]

**Review by RyanSkraba — APPROVED** [review]
This almost LGTM -- it seems the docker image that we use for releases (based on debian `stretch`) is still 3.5.3 and there isn't any 3.6 available for it.

You can merge this safely now, but the next release is going to need a fix to the environment!

**Comment by kojiromike** [comment]
@RyanSkraba the mega base image is always going to be a sticking point. We have looked at nektos/act as a substitute, but it isn't free from trouble.

**Comment by RyanSkraba** [comment]
For reference, I created https://issues.apache.org/jira/browse/AVRO-3092 to discuss that issue and PR#1155 for a quick fix!  But we can probably do better for a long-term solution.

**Pull request merged**
