### PR TITLE
AVRO-3030: Remove the PUBLIC_DEPRECATED

### PR DESCRIPTION
**Pull request by Fokko**
Make sure you have checked _all_ steps below.

### Jira

- [ ] My PR addresses the following [Avro Jira](https://issues.apache.org/jira/browse/AVRO/) issues and references them in the PR title. For example, "AVRO-1234: My Avro PR"
  - https://issues.apache.org/jira/browse/AVRO-XXX
  - In case you are adding a dependency, check if the license complies with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).

### Tests

- [ ] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

### Commits

- [ ] My commits all reference Jira issues in their subject lines. In addition, my commits follow the guidelines from "[How to write a good git commit message](https://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [ ] In case of new functionality, my PR adds documentation that describes how to use it.
  - All the public functions and the classes in the PR contain Javadoc that explain what it does

### CODE REVIEW

**Review by RyanSkraba — APPROVED** [review]

**Comment by RyanSkraba** [comment]
This looks good to me -- but just a quick thought: 

`PUBLIC_DEPRECATED` might still  be useful for developers changing their specific compiler settings from PUBLIC to PRIVATE, to warn their downstream projects that a breaking change is coming to their generated classes.

I don't think that's an _extremely_ common use case: as far as I know, we never share generated classes at our company (and only share schemas).  What do you think?

**Comment by Fokko** [comment]
The `PUBLIC_DEPRECATED` has been the default since 1.7.4, so the downstream projects should get the warnings for a while. I like to remove this limbo state, and either force users to go public or private (and use the getters and setters). This reduces the noise in the generated templates.

I use the generated classes a lot, and this should not be a problem to me, I prefer to use the getters/setters.

**Comment by Fokko** [comment]
I'll target this for 1.11

**Comment by RyanSkraba** [comment]
Thanks for the confirmation and the cleanup!  :+1:

**Pull request merged**
