### PR TITLE
AVRO-3205 Rust: Update Cargo.toml [package] information

### PR DESCRIPTION
**Pull request by martin-g**
### Jira

- [X] My PR addresses the following [AVRO-3205](https://issues.apache.org/jira/browse/AVRO-3205) issue.

### Tests

- [X] My PR does not need testing for this extremely good reason: Only `[package]` in Cargo.toml is being changed 

### Commits

- [X] My commits all reference Jira issues in their subject lines.
 
### Documentation

- [X] No need of documentation

### CODE REVIEW

**Comment by martin-g** [comment]
@iemejia Could you please review this PR ? Thank you!

**Comment by martin-g** [comment]
> src/schema_compatibility.rs:845:    // https://github.com/flavray/avro-rs/pull/76

This is still useful! The comment could be removed once the issue/limitation is solved!

**Comment by ultrabug** [comment]
> Any idea / tracking about this timing? no actual members of the project can manage this while it's done?

friendly bump @martin-g

**Comment by martin-g** [comment]
@ultrabug I also have several PRs waiting for approval and merge ...

@RyanSkraba @iemejia Please vote me as a committer ! :-)

**Comment by ultrabug** [comment]
(yep I saw that Martin)

@RyanSkraba @iemejia **please** :+1:

**Comment by ultrabug** [comment]
Hello, and happy (and healthy) new year to everyone!

I'd like to friendly bump this PR to get an update on the Rust maintenance for Apache Avro? We've been stuck (and patient) for a very long time now...

**Comment by martin-g** [comment]
Happy New Year, @ultrabug !
https://lists.apache.org/thread/67jcrd0bq8knxmv6loqchmt5g4q7ry27

**Comment by ultrabug** [comment]
OMG congratulations @martin-g :hugs:

**Pull request merged**
