### PR TITLE
Add FreeBSD way of byte-swapping uint32

### PR DESCRIPTION
**Pull request by AMDmi3**

### CODE REVIEW

**Comment by rdblue** [comment]
@thiru-apache, can you take a look at this? It's a pretty small patch.

**Comment by rdblue** [comment]
@AMDmi3, could you open a JIRA issue for this and add the issue ID to the description? (For example, "AVRO-1234: Add FreeBSD ...")

**Comment by thiru-apache** [comment]
@rdblue/@AMDmi3, 

Looks good to me. Will merge it once the ticket is created.

**Comment by busbey** [comment]
@AMDmi3 do you have an ASF JIRA user id? I can file the issue, but would prefer to credit you in the assignee field.

**Comment by AMDmi3** [comment]
I don't care of being credited and would prefer not to deal with JIRA in any way.

**Pull request merged**
