### PR TITLE
AVRO-3589: Update github actions versions

### PR DESCRIPTION
**Pull request by iemejia**
R: @RyanSkraba or @martin-g

### CODE REVIEW

**Comment by martin-g** [comment]
Would it be a good idea to add a new dependabot entry too ? Or we want to do this manually ?
See https://github.com/marketplace/actions/docker-setup-buildx#keep-up-to-date-with-github-dependabot

**Comment by iemejia** [comment]
Oh I was not aware dependabot did it too. Let me just do the PR for dependabot, let me ping you back.

**Comment by martin-g** [comment]
No need of separate PR.
Just add an entry to https://github.com/apache/avro/blob/master/.github/dependabot.yml and it will send us PRs next time there is a new version of an action.

**Comment by iemejia** [comment]
Done, thanks for the info 👍

**Comment by martin-g** [comment]
Cool!
Let's wait for the 69 CI checks to run and pass! :-)

**Comment by iemejia** [comment]
Argh I cannot figure out why that specific test is failing 🤔

**Comment by martin-g** [comment]
I've re-ran the failed job and now it is all green!
It seems it was a temporary glitch in the Matrix.

**Comment by iemejia** [comment]
Cool, I am going to go ahead then and merge it, we can always rollback one if it becomes really flaky.

**Pull request merged**
