### PR TITLE
[C++] Fix main page for Doxygen.

### PR DESCRIPTION
**Pull request by mkmkme**
## What is the purpose of the change

Doxygen doesn't have a `\ul` tag and therefore it's currently displayed as a plain text on a web page. This commit removes it.

## Verifying this change

This change is a trivial rework / code cleanup without any test coverage.
## Documentation

- Does this pull request introduce a new feature? **no**

### CODE REVIEW

**Comment by martin-g** [comment]
We will need JIRA issues for the changelog:
- go to https://selfserve.apache.org/jira-account.html and request a JIRA account
- once you have an account you can create a new issue at https://issues.apache.org/jira/browse/AVRO
- the PR title should start with `AVRO-1234: ` (the actual id) and the PR description should have a link to the JIRA issue
- the commit messages should start with `AVRO-1234: `. No need to force-push - we squash the commits anyway.

**Comment by martin-g** [comment]
This PR is trivial, so no issue is needed!

**Comment by mkmkme** [comment]
I've requested a jira login for the future anyways :) Will follow this for the next PRs.

**Comment by martin-g** [comment]
Thank you, @mkmkme !

**Pull request merged**
