### PR TITLE
AVRO-3621: [Rust] do not log each error while validating against union variants

### PR DESCRIPTION
**Pull request by shaeqahmed**
Follow-up on: https://github.com/apache/avro/pull/1837#discussion_r955853650

### Jira

https://issues.apache.org/jira/browse/AVRO-3621

### Tests

- Adds a unit test assertion based on updated behavior, to assert that each validation check is no longer producing error logs when resolving against unions.

### CODE REVIEW

**Comment by martin-g** [comment]
Awesome!

I've made a small improvement to the panic message for `assert_not_logged()` because with `assert_ne!()` it was a bit confusing: `left != right. Left: X, Right: X`

Waiting for the CI to pass and I will merge it!

**Comment by shaeqahmed** [comment]
> Awesome!
> 
> I've made a small improvement to the panic message for `assert_not_logged()` because with `assert_ne!()` it was a bit confusing: `left != right. Left: X, Right: X`
> 
> Waiting for the CI to pass and I will merge it!

Clarifying the message sounds good to me, but hm from what I understood the thread local LOG_MESSAGES is shared between multiple test cases sequentially, and only cleared at the end so merely checking for the presence of a `_last_log` without comparing it to the unexpected value wouldn't be correct right? I've updated with what I think should be the correct behavior:

```Rust
    match LOG_MESSAGES.borrow().last() {
        Some(last_log) if last_log == unexpected_message => panic!(
            "The following log message should not have been logged: '{}'",
            unexpected_message
        ),
        _ => (),
    }
```

**Comment by martin-g** [comment]
Ouch! I simplified it so much that it is wrong now indeed!

**Comment by martin-g** [comment]
Your suggestion has been committed!
Thanks for the catch!

**Pull request merged**
