### PR TITLE
AVRO-1329: Extended enums

### PR DESCRIPTION
**Pull request by unchuckable**
Sorry this took a little. Corona and RL made me have to deal with other issues before this one.
Feedback welcome. I tried to provide the functionality of AVRO-1329 along with some suitable yet compatible changes to the public API, but am well willing to make changes as deemed appropriate.

Thanks, and stay safe.

---8<------

Make sure you have checked _all_ steps below.

### Jira

- [X] My PR addresses the following [Avro Jira](https://issues.apache.org/jira/browse/AVRO/) issues and references them in the PR title. For example, "AVRO-1234: My Avro PR"
  - https://issues.apache.org/jira/browse/AVRO-1329

### Tests

- [X] My PR adds the following unit tests:
 - TestSchema.testExtendedEnumSchemaSerializeAndDeserialize
 - TestSchema.testSimpleEnumSchemaSerialize
 - Updates/Extensions to Compiler Unit tests

### Commits

- [X] My commits all reference Jira issues in their subject lines. In addition, my commits follow the guidelines from "[How to write a good git commit message](https://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [X] In case of new functionality, my PR adds documentation that describes how to use it.
  - All the public functions and the classes in the PR contain Javadoc that explain what it does

### CODE REVIEW

**Comment by unchuckable** [comment]
Dunno what these CI issues are, can anyone help there?

**Comment by unchuckable** [comment]
@Humbedooh Hi, Daniel. Can you please elaborate as to why this ticket is being closed?

**Comment by martin-g** [comment]
https://issues.apache.org/jira/browse/INFRA-25047

**Comment by unchuckable** [comment]
@KalleOlaviNiemitalo, @martin-g  Thanks for the explanation. Makes sense. Nice to see not only us have a use case for this. Basically, what I would like to add at a later point, would be enum symbol aliases similar to field aliases, that would help us a lot in schema evolution.
I think I'll try to rebase this to current versions and re-submit a pull request with the new main branch.

**Comment by martin-g** [comment]
Hovering over the `Reopen and comment` button below shows this hint: `The repository that submitted this pull request has been deleted` :-/

**Comment by unchuckable** [comment]
Interesting. Something must have been screwed up there. Will recreate the change to the best of my ability ;)

**Comment by unchuckable** [comment]
Found the original code again, will rebase onto current main and resubmit the pull request these days.

**Pull request closed without merging**
