### PR TITLE
[WIP] Remove Guava

### PR DESCRIPTION
**Pull request by Fokko**
Commons and Jackson are already upgraded.

https://issues.apache.org/jira/projects/AVRO/issues/AVRO-2217

### CODE REVIEW

**Comment by nandorKollar** [comment]
@Fokko looks like there is no 14.0.2 from Guava, but 14.0.1

**Comment by Fokko** [comment]
Oops, that's a typo, thanks @nandorKollar. I've did a small bump since Guava is always dangerous to update. To keep compatibility, I've looked at several projects, and a couple of them use `14.0.1` :-)

**Comment by nandorKollar** [comment]
@Fokko there's a comment above the change, saying we should use the same as Hadoop. Not sure if it is still relevant, but is Hadoop using 14.0.1? In case the comment is not relevant any more, then can we also delete it?

**Comment by Fokko** [comment]
Thanks @dkulp for the suggestion. I just checked, and Guava is only used in a couple of tests. Let me open a new PR where we get rid of the guava.

**Pull request closed without merging**
