### PR TITLE
AVRO-3131: Drop support for Node.js 10

### PR DESCRIPTION
**Pull request by iemejia**
R: @RyanSkraba

### CODE REVIEW

**Comment by RyanSkraba** [comment]
What's the deal with Node 14?  It hasn't always been broken has it?

**Review by RyanSkraba — APPROVED** [review]

**Review by RyanSkraba — COMMENTED** [review]
Ooops, can you update https://github.com/apache/avro/blob/master/BUILD.md#L13 at the same time?

**Comment by iemejia** [comment]
Good catch for BUILD.md, I will update. The Node failure is quite odd I thought augmenting the timeout will do it but it is not the case. I tried with node 16 (next LTS) and there are more failing tests so it will require a more detailed revision :s

**Comment by iemejia** [comment]
Merging this since failing tests are unrelated to this PR. For reference [AVRO-3140](https://issues.apache.org/jira/browse/AVRO-3140)

**Pull request merged**
