### PR TITLE
AVRO-3182 fix union schema ToString() has an extra type property

### PR DESCRIPTION
**Pull request by yxmm-wxe**
Make sure you have checked _all_ steps below.

### Jira

- [x] My PR addresses the following [Avro Jira](https://issues.apache.org/jira/browse/AVRO/) issues and references them in the PR title. For example, "AVRO-1234: My Avro PR"
  - https://issues.apache.org/jira/browse/AVRO-3182
  - In case you are adding a dependency, check if the license complies with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).

### Tests

- [x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

### Commits

- [x] My commits all reference Jira issues in their subject lines. In addition, my commits follow the guidelines from "[How to write a good git commit message](https://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [x] In case of new functionality, my PR adds documentation that describes how to use it.
  - All the public functions and the classes in the PR contain Javadoc that explain what it does

### CODE REVIEW

**Review by RyanSkraba — CHANGES_REQUESTED** [review]
Hi!  I've set the Fix Version of the JIRA to 1.11.0 -- this is obviously wrong behaviour right now!

You're probably stronger than me in C# ... would it be possible to (1) add a unit test that demonstrates the fix and (2) check that this doesn't have any impact on a field with a UNION?  I can't seem to figure out why UnionSchema was included here in the first place, and I'd like to avoid a regression!

Are the Code scanning warnings something we can do something about?

Once again, thanks for your patience and your contribution!

**Comment by yxmm-wxe** [comment]
Hi, thank you for your comment.

1) I have added the unit test that demonstrates the fix.

2) I'm not clear why UnionSchema was included here in the first place, but I found Shema.ParseJson is compatible with both cases: [Parse union schema json without type property](https://github.com/apache/avro/blob/master/lang/csharp/src/apache/main/Schema/Schema.cs#L174) and [Parse union schema json with type property](https://github.com/apache/avro/blob/master/lang/csharp/src/apache/main/Schema/Schema.cs#L203) 

3) About the Code scanning warnings.  
Firstly, the Schema is an abstract class, so I don't think it will introduce a dependency circle. And this code is written like this at the beginning.  
Secondly, it is strange to me to judge the derived class in the parent class.  
So I override ToString() in PrimitiveSchema separately.

**Comment by RyanSkraba** [comment]
Thanks so much -- I wasn't sure what the code scanning warnings meant, so thanks for going deeper into those.

This LGTM, let's see if any C# experts weigh in over the next few days!

**Review by RyanSkraba — APPROVED** [review]

**Comment by yxmm-wxe** [comment]
I am troubled with the previous code implementation. My changes trigger the code scan warning again. I guess there is no code scanning at the first commit.

@RyanSkraba Please help approve running workflows again. Thank you very much!

**Comment by RyanSkraba** [comment]
I'm not too worried about _existing_ CodeQL scanning warnings, although i appreciate that you took a bit of extra time to fix them.  When you are happy with your solution, let me know!

**Comment by yxmm-wxe** [comment]
@RyanSkraba I have fixed all CodeQL scanning warnings in my changes. Maybe I have code cleanliness. (^_^) Thanks for your appreciation.

**Comment by RyanSkraba** [comment]
Thanks for the contribution!

**Pull request merged**
