### PR TITLE
AVRO-1902: C: Namespace "" means space = NULL.

### PR DESCRIPTION
**Pull request by walshb**

### CODE REVIEW

**Comment by walshb** [comment]
Oh yes, good point. Updated.

**Comment by c4urself** [comment]
@johnsgill3 @walshb -- any progress here?

**Comment by walshb** [comment]
I have no idea. All the people with commit access in Avro land don't seem to understand C. I have 4 patches which the just ignore. I'm no longer using Avro so I've just given up.

If you are interested in getting this fixed, I suggest finding the last person who committed a significant change to the C code (ie. someone with commit access, who cares about C), and contacting them directly.

**Comment by walshb** [comment]
@dkulp That is awesome! Thank you very much!

Sorry to trouble you further, but please would you mind taking a look at some other Avro-C pull requests?

https://github.com/apache/avro/pull/398
https://github.com/apache/avro/pull/159
https://github.com/apache/avro/pull/160

Thanks again.

**Pull request merged**
