### PR TITLE
AVRO-3407: Test for user metadata in the interop tests

### PR DESCRIPTION
**Pull request by martin-g**
### Jira

- [X] My PR addresses the following [Avro Jira](https://issues.apache.org/jira/browse/AVRO/) issues and references them in the PR title. For example, "AVRO-1234: My Avro PR"
  - https://issues.apache.org/jira/browse/AVRO-3407

### Tests

- [X] My PR adds new interop tests

### Commits

- [X] My commits all reference Jira issues in their subject lines. In addition, my commits follow the guidelines from "[How to write a good git commit message](https://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- No need of new docs

### CODE REVIEW

**Comment by martin-g** [comment]
@zcsizmadia Want to join the party with C# test for the user metadata ?

**Comment by martin-g** [comment]
> By piggy backing your existing branchand just add the matching C# piece?

This or wait for this PR to be merged and then against master. I will probably merge it tomorrow.

**Comment by zcsizmadia** [comment]
@martin-g https://github.com/apache/avro/pull/1553

That PR is into your branch and not against master

**Comment by zcsizmadia** [comment]
Sorry fro the noise. I cleaned up the mess and https://github.com/apache/avro/pull/1554 shoudl be good PR into your branch to add C# support

**Comment by martin-g** [comment]
> Are you planning to remove the `if (userMetadata != null)` checks from all languages after all the langs add the user_metadata? I assume you have the check no to break the tests in langs which do not have user_metadat yet?

Yes, that's the plan!

**Pull request merged**
