### PR TITLE
Add Single Object Encoding Support to Ruby library

### PR DESCRIPTION
**Pull request by jszmajda**
This patch adds support for the [Single Object Encoding Spec](http://avro.apache.org/docs/current/spec.html#single_object_encoding_spec).

I translated the code from Java to Ruby.

I believe this is a performant implementation in Ruby.

I'm not sure this is the right place for this code, but I couldn't think of a better one. Definitely open to suggestions / feedback!

Hope this helps,

### CODE REVIEW

**Comment by jszmajda** [comment]
Hello! FWIW the team at Optoro has been using this branch for a couple years now with no regressions. Is there any way to merge this into master? Thanks!

**Comment by Fokko** [comment]
Thanks @jszmajda for the feedback. LGTM

**Comment by Fokko** [comment]
@jszmajda One more thing, can you open a Jira ticket for this? This is required for keeping track of the changelogs. Thanks!

**Comment by Ingvar-Y** [comment]
@Fokko I created [https://jira.apache.org/jira/projects/AVRO/issues/AVRO-2538](https://jira.apache.org/jira/projects/AVRO/issues/AVRO-2538)

Can this be included in 1.9.1?

**Comment by Ingvar-Y** [comment]
@Fokko gentle ping: can you review and/or merge this?

It closes [AVRO-2538](https://jira.apache.org/jira/projects/AVRO/issues/AVRO-2538) and [AVRO-1740](https://jira.apache.org/jira/browse/AVRO-1740) (I should have probably just pointed to AVRO-1740 but missed it the first time around).

**Comment by Fokko** [comment]
Excuse me @Ingvar-Y for not responding. I think I've missed a message somewhere. I think this is ready to be merged.

**Comment by ypt** [comment]
Hi @jszmajda (or anyone else using the Ruby single object encoding implementation from this PR), are you using the output of the Ruby `Avro::Schema.single_object_schema_fingerprint` or `Avro::Schema..single_object_encoding_header` methods? And if yes, have you compared it to the output from other languages?

I've compared the output of the [Ruby implementation](https://github.com/apache/avro/blob/release-1.10.0/lang/ruby/lib/avro/schema.rb#L180) to the [Java implementation](https://github.com/apache/avro/blob/release-1.10.0/lang/java/avro/src/main/java/org/apache/avro/SchemaNormalization.java#L64), and it seems like the output of the Ruby implementation of `single_object_schema_fingerprint` is reversed in comparison.

I believe that this is caused by [unnecessarily reversing the array traversal here](https://github.com/apache/avro/blob/release-1.10.0/lang/ruby/lib/avro/schema.rb#L184) during the bit mask + shift operation that constructs the little endian fingerprint for the message header.

I've filed a Jira ticket here to track this:
https://issues.apache.org/jira/browse/AVRO-2907

Hoping to hear if there's more to the story here and get some guidance on how to proceed. I'm happy to submit a PR that updates the Ruby implementation if folks feel ok with that.

**Comment by jszmajda** [comment]
Hey @ypt! I built this for my last company but I've since left and haven't needed it. @yarmiganosca may have more detail on its use in practice. FWIW we were using it in an entirely ruby shop, so didn't need to interop with Java.

For the encoding direction - I copied over the tests from the Java code and reimplemented things. It's entirely possible I got the order backwards!! 

If you need to interop with Java I'd say let's trust the Java version and update this if needed. But it would introduce a breaking change :(

**Pull request merged**
