### PR TITLE
AVRO-1697: Add support for the Snappy codec

### PR DESCRIPTION
**Pull request by dasch**
This allows reading and writing snappy-compressed data using the Ruby library.

I haven't added a hard dependency on the `snappy` gem, as I figure people shouldn't be forced to install it if they're not using the codec anyway. However, this means that users _must_ require the `snappy` gem themselves.

### CODE REVIEW

**Comment by busbey** [comment]
Please file an issue on the project tracker: https://issues.apache.org/jira/browse/AVRO/

Also please try to coordinate with the solution in #31

**Comment by dasch** [comment]
@busbey https://issues.apache.org/jira/browse/AVRO-1697

**Comment by busbey** [comment]
Can we add better detection of when the snappy gem isn't present and fail gracefully?

**Comment by dasch** [comment]
Sure, I'll try lazy-requiring it.

**Comment by dasch** [comment]
@busbey how does this look?

**Comment by dasch** [comment]
Merged into trunk.

**Pull request closed without merging**
