### PR TITLE
Add missing ASF headers in rust files

### PR DESCRIPTION
**Pull request by jbonofre**
## What is the purpose of the change

A couple of files are missing ASF headers, and so rat is complaining.

## Verifying this change

This change is a trivial rework / code cleanup without any test coverage.

## Documentation

- Does this pull request introduce a new feature? no

### CODE REVIEW

**Review by Fokko — APPROVED** [review]
Great catch @jbonofre Thanks for fixing this 🙌

**Comment by martin-g** [comment]
Actually those files shouldn't have been committed at all!
I am not sure when and how I added them without noticing. 
I'll remove them as soon as I am in front of my dev machine!
Please don't make a release with them! The config.yaml will break others' builds.

**Comment by jbonofre** [comment]
@martin-g thanks ! Indeed I was surprised to see these files on the 1.11 branch but not on main. Let me know if you want me to create a PR to delete those files.

**Comment by martin-g** [comment]
Thanks, @jbonofre !
I've just removed them!
Actually the config.yaml was named config.yaml.disabled, so it was not problematic. Anyway, it is removed now!

**Comment by jbonofre** [comment]
@martin-g thanks !

**Pull request merged**
