### PR TITLE
AVRO-2336: Use Java Standard Charsets - Part 2

### PR DESCRIPTION
**Pull request by BELUGABEHR**

### CODE REVIEW

**Comment by dkulp** [comment]
This looks fine, but has a conflict in SchemaBuilder.java.   Can you rebase and resolve?  Thanks!

**Comment by BELUGABEHR** [comment]
Thanks for the review @dkulp ! Submitting rebase now.

**Comment by BELUGABEHR** [comment]
May want to wait for #481

**Comment by dkulp** [comment]
I merged #481.   Thus, you'll need to rebase this (and your other) PR and fix the various conflicts.

**Comment by iemejia** [comment]
@BELUGABEHR We introduced automatic code formatting and this PR broke. I have finished my 'massive' changes now. So can you please rebase this one.

**Comment by iemejia** [comment]
We introduced automatic code formatting. For more info see the "[How to contribute](https://cwiki.apache.org/confluence/display/AVRO/How+To+Contribute)" page. This  probably affected this PR can you please rebase it.

**Comment by iemejia** [comment]
@BELUGABEHR any chance this one can getupdated quickly to make it before the cut?

**Comment by BELUGABEHR** [comment]
@iemejia Would be my pleasure.  Just pushed a fresh copy.

**Pull request merged**
