### PR TITLE
AVRO-2563: Add data interop test for the JavaScript bindings

### PR DESCRIPTION
**Pull request by sekikn**
Make sure you have checked _all_ steps below.

### Jira

- [x] My PR addresses the following [Avro Jira](https://issues.apache.org/jira/browse/AVRO/) issues and references them in the PR title. For example, "AVRO-1234: My Avro PR"
  - https://issues.apache.org/jira/browse/AVRO-2563
  - In case you are adding a dependency, check if the license complies with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).

### Tests

- [x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

* Added lang/js/test/interop_data_generate.js to test if the other languages can read the files JS generated
* Added lang/js/test/interop_data_test.js to test if JS can read the files the other languages generated

### Commits

- [x] My commits all reference Jira issues in their subject lines. In addition, my commits follow the guidelines from "[How to write a good git commit message](https://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [x] In case of new functionality, my PR adds documentation that describes how to use it.
  - All the public functions and the classes in the PR contain Javadoc that explain what it does

### CODE REVIEW

**Comment by sekikn** [comment]
Rebased on master and fixed some minor issues.

**Comment by kojiromike** [comment]
This is great work, thanks. Please ensure that the root build.sh actually runs the js linter during travisci tests. (Until linting is fixed in every language, I think we should run `(cd lang/js && ./build.sh lint test)` directly in the test subcommand.

**Comment by sekikn** [comment]
Thanks for the review @kojiromike!

> Please ensure that the root build.sh actually runs the js linter during travisci tests.

Exactly. So I submitted #705, [which is intended to be merged after this PR](https://github.com/apache/avro/pull/705#issuecomment-552050703), and [I confirmed that change ran linters in Travis](https://travis-ci.org/apache/avro/jobs/609502809#L15563) (that Travis job failed because it was executed before merging this PR). Sorry that these PRs are somewhat complicated.

**Comment by kojiromike** [comment]
@sekikn That is fine, I just misunderstood. Do you want me to merge this? (You have a few outstanding PRs. I'm happy to merge them, but I was under the impression you had commit rights and I didn't want to disrupt your process.)

**Comment by sekikn** [comment]
@kojiromike, I don't have commit rights since I'm not an Avro committer. I'd appreciate if you merge them!

**Comment by sekikn** [comment]
Thanks for merging @kojiromike! I'll kick the CI for #705 and confirm the JS linter succeeds this time.

**Pull request merged**
