### PR TITLE
AVRO-1901: Record named Exception generated bad code

### PR DESCRIPTION
**Pull request by benmccann**
Backport to branch-1.7

### CODE REVIEW

**Comment by busbey** [comment]
this backport misses the test record named "Exception" in share/test/schemas/specialtypes.avdl that's present on master and branch-1.8. Was there a particular need to exclude it?

**Comment by benmccann** [comment]
That file does not exist on branch-1.7: https://github.com/apache/avro/tree/branch-1.7/share/test/schemas

**Comment by busbey** [comment]
that's a good reason. 😸 

We can add it in if AVRO-1614 ends up backported to 1.7.

**Comment by busbey** [comment]
I pushed this to branch-1.7. github won't autoclose this PR until a commit hits master referencing it. If you have a chance @benmccann, please close it. Otherwise I'll push a bulk close later.

**Comment by benmccann** [comment]
Thanks!!

**Pull request closed without merging**
