### PR TITLE
[fix] AVRO-2418

### PR DESCRIPTION
**Pull request by zolyfarkas**
Unit test to reproduce issue at: TestUnionPromotion.

### CODE REVIEW

**Comment by nandorKollar** [comment]
@zolyfarkas this looks very similar to AVRO-2415 (#537)

**Comment by zolyfarkas** [comment]
It is actually the same issue, impacts both arrays and maps…

The fix is identical, 
 we should probably merge in the PR from AVRO-2415, maybe we should add a test case for maps to it…

Updated the JIRA to reflect that it duplicates AVRO-2415, also aded a comment to the #537 <https://github.com/apache/avro/pull/537> PR.

cheers.

—Z

**Comment by nandorKollar** [comment]
Actually I think #526 is the one which is going to be merged, it seems that the fix there is not identical, a bit different approach was taken.

**Comment by zolyfarkas** [comment]
I am not sure #526 fixes the issue though… the PR should contains tests to validate that.

—Z

**Comment by Fokko** [comment]
Thanks for the fix @zolyfarkas, can you check if the issue still exists on master?

**Comment by unchuckable** [comment]
Issue still exists. Added a test case for the map case to #537, because it's basically the same fix as this one.

**Comment by nandorKollar** [comment]
#537 is merged, I think this PR can be closed.

**Comment by dkulp** [comment]
Closed as fixed as part of #537

**Pull request closed without merging**
