### PR TITLE
AVRO-2948: Replace Deprecated Probot PR Labeler with Github Action

### PR DESCRIPTION
**Pull request by kbendick**
Make sure you have checked _all_ steps below.

### Jira

- [x] My PR addresses the following [Avro Jira](https://issues.apache.org/jira/browse/AVRO/) issues and references them in the PR title. For example, "AVRO-1234: My Avro PR"
  - https://issues.apache.org/jira/browse/AVRO-2948
  - In case you are adding a dependency, check if the license complies with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x). - This labeler is being used in several other ASF repos. 

### Tests

- [x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason: It is not possible to write unit tests for the probot labeler. However, I have tested a similar config change I made in the Iceberg repo and you can see the links to the tests in this issue: https://github.com/apache/iceberg/issues/1649

I also merged in this config into my local fork and then changed a Dockerfile and it was appropriately labeled as `Build`: https://github.com/kbendick/avro/pull/2

### Commits

- [x] My commits all reference Jira issues in their subject lines. In addition, my commits follow the guidelines from "[How to write a good git commit message](https://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [x] In case of new functionality, my PR adds documentation that describes how to use it.
  - No new functionality is added to the Avro codebase. PR labels will be applied to new PRs and PRs that receive new pushes.

### CODE REVIEW

**Comment by kbendick** [comment]
cc @rdblue

**Comment by rdblue** [comment]
+1

@kbendick moved the Iceberg project over to this labeller as well. It works the same way as far as we've seen and the old one is deprecated, so I think we should merge this. I'll go ahead and merge if there aren't any objections in the next couple days.

@iemejia and @Fokko, you may want to look at this since you committed the probot labeller config.

**Review by nandorKollar — APPROVED** [review]

**Review by Fokko — APPROVED** [review]
Thanks for fixing this @kbendick

**Comment by rdblue** [comment]
Looks like PHP is failing the build. I'll wait to merge this until the build is working again.

**Comment by Fokko** [comment]
Looks like @RyanSkraba fixed the CI in https://github.com/apache/avro/pull/971 :)

**Comment by rdblue** [comment]
Great! I kicked off another CI run.

**Comment by Fokko** [comment]
I think we have to rebase once more, I've just merged #971

**Comment by Fokko** [comment]
All green let's move this forward!

**Pull request merged**
