### PR TITLE
AVRO-1340: use default to allow old readers to specify default enum v…

### PR DESCRIPTION
**Pull request by ksenji**
…alue when encountering new enum symbols

### CODE REVIEW

**Comment by ig-michaelpearce** [comment]
+1 - about time too avro supported this :) this solves a lot of our pain

**Comment by iemejia** [comment]
We introduced automatic code formatting. For more info see the "[How to contribute](https://cwiki.apache.org/confluence/display/AVRO/How+To+Contribute)" page. This  probably affected this PR can you please rebase it.

**Comment by raphaelauv** [comment]
Should we close this PR since this one https://github.com/apache/avro/pull/357 have been merged ?

**Comment by iemejia** [comment]
@cutting since you are aware of the current status of the spec, WDYT? probably worth closing.

**Comment by cutting** [comment]
Yes, I think we can close this.  Thanks.

**Pull request closed without merging**
