### PR TITLE
AVRO-2390: Travis jobs are killed with "No output has been received"

### PR DESCRIPTION
**Pull request by nandorKollar**
https://jira.apache.org/jira/browse/AVRO-2390

### CODE REVIEW

**Comment by nandorKollar** [comment]
Hm, travis_wait doesn't seems to help, @Fokko do you have any idea what could be the problem? Builds are failing in various places with the same error from Travis, I thought that a simple travis_wait would fix it, but looks like it doesn't.

**Comment by kojiromike** [comment]
Is there something keeping a network socket open after the tests complete? Just taking a swing in the dark based on NLog/NLog#3282

**Comment by Fokko** [comment]
The issue is that some process is hanging, and therefore it will not continue. Travis kills the CI job because there isn't any activity, and it is taking resources. We have to drill down into the statement and see why it doesn't terminate.

**Comment by Fokko** [comment]
The errors look arbitrary. I think this is an issue on the Travis side: https://www.traviscistatus.com/

**Comment by Fokko** [comment]
This was an issue on the Travis side

**Comment by nandorKollar** [comment]
Great, thanks Fokko!

**Pull request closed without merging**
