### PR TITLE
AVRO-3721 Support Python 3.10; Fix Annotations

### PR DESCRIPTION
**Pull request by kojiromike**
### Jira

- [x] Addresses [AVRO-3721](https://issues.apache.org/jira/browse/AVRO-3271)
- [x] References the issue in the PR title.
- [x] Adds no new dependencies.

### Tests

- [x] Adds tests for Python 3.10.

### Commits

- [x] Commits all reference Jira issues in their subject lines.
- [x] In addition, my commits follow the guidelines from "[How to write a good git commit message](https://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [x] N/A

### CODE REVIEW

**Comment by RyanSkraba** [comment]
Thanks for the fix!

Minor note for the history: the commit name points to the wrong JIRA, this is AVRO-3271.  I've corrected the link in JIRA, no big deal!  Should these be cherry-picked to branch-1.11 ?

**Comment by kojiromike** [comment]
Hi, Ryan,

Oops, sorry about the numeric error.

I'm all for cherry picking, but only if it's easy. The test change doesn't make any functional difference. Maybe a few folks will choose not to use that version of avro because they're dead set on using Python 3.10 and we didn't advertise that it works. I doubt it's significant.

The typing change likewise won't make any difference at runtime, but for the folks using type checking, the sooner they get access to accurate type hints, the better.

**Comment by martin-g** [comment]
Some lint checks started failing recently - https://github.com/apache/avro/runs/4998750906?check_suite_focus=true
```
lint create: /home/runner/work/avro/avro/lang/py/.tox/lint
lint installdeps: black, isort
lint inst: /home/runner/work/avro/avro/lang/py/.tox/.tmp/package/1/avro-1.12.0+snapshot-py2.py3-none-any.whl
lint installed: avro @ file:///home/runner/work/avro/avro/lang/py/.tox/.tmp/package/1/avro-1.12.0%2Bsnapshot-py2.py3-none-any.whl,black==22.1.0,click==8.0.3,isort==5.10.1,mypy-extensions==0.4.3,pathspec==0.9.0,platformdirs==2.4.1,tomli==2.0.0
lint run-test-pre: PYTHONHASHSEED='4249405946'
lint run-test: commands[0] | black --check .
would reformat avro/io.py
would reformat avro/schema.py

Oh no! 💥 💔 💥
2 files would be reformatted, 37 files would be left unchanged.
ERROR: InvocationError for command /home/runner/work/avro/avro/lang/py/.tox/lint/bin/black --check . (exited with code 1)
```

**Comment by kojiromike** [comment]
Looks like the stable release of black has changed its opinion on a couple of stylistic points. I will make a pr.

**Comment by martin-g** [comment]
Thanks, @kojiromike !
I've tried to fix it myself but I wasn't able to make `tox` working here. Python complains that some packages are not available, like `py.io` or `packaging.requirements`:

```
python3.10 -m tox -e lint
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 187, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.10/runpy.py", line 146, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib/python3.10/runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "/home/martin/.local/lib/python3.10/site-packages/tox/__init__.py", line 32, in <module>
    from .session import cmdline  # isort:skip
  File "/home/martin/.local/lib/python3.10/site-packages/tox/session/__init__.py", line 22, in <module>
    from tox.config import INTERRUPT_TIMEOUT, SUICIDE_TIMEOUT, TERMINATE_TIMEOUT, parseconfig
  File "/home/martin/.local/lib/python3.10/site-packages/tox/config/__init__.py", line 24, in <module>
    from packaging import requirements
ImportError: cannot import name 'requirements' from 'packaging' (unknown location)
```

**Comment by kojiromike** [comment]
See #1489

**Comment by kojiromike** [comment]
@martin-g Hmm, I can't easily explain what's going on with your setup. Did you try updating tox and doing `git clean -ixdf` to force a completely fresh start?

**Comment by martin-g** [comment]
`git clean -ixdf` didn't help too.
Anyway, it is not important for me to run the linter locally.
Thanks for fixing the CI, @kojiromike !

**Pull request merged**
