### PR TITLE
AVRO-2945: Add CPAN trademark clarification.

### PR DESCRIPTION
**Pull request by RyanSkraba**
Make sure you have checked _all_ steps below.

### Jira

- [X] My PR addresses the following [Avro Jira](https://issues.apache.org/jira/browse/AVRO/) issues and references them in the PR title. For example, "AVRO-1234: My Avro PR"
  - https://issues.apache.org/jira/browse/AVRO-2945
  - In case you are adding a dependency, check if the license complies with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).

### Tests

- [X] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:
Documentation only

### Commits

- [X] My commits all reference Jira issues in their subject lines. In addition, my commits follow the guidelines from "[How to write a good git commit message](https://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [ ] In case of new functionality, my PR adds documentation that describes how to use it.
  - All the public functions and the classes in the PR contain Javadoc that explain what it does

### CODE REVIEW

**Comment by RyanSkraba** [comment]
@justinmclean Could you verify this is an alright wording?  Regarding this [thread](https://lists.apache.org/thread.html/r1ef7be5a31b600cc579a490df48b44797cc28bd145f549f13c9d3ba5%40%3Cdev.avro.apache.org%3E) and [this artifact](https://metacpan.org/pod/release/SEKIKN/Avro-1.10.0/lib/Avro.pm) on CPAN.

**Comment by justinmclean** [comment]
HI,

That looks OK to me. I would put in a link to the apache project if possible.

Thanks,
Justin

**Review by iemejia — APPROVED** [review]
LGTM

**Comment by RyanSkraba** [comment]
Cherry-picked to [branch-1.10](https://github.com/apache/avro/commit/0a8ec0f87e367e26cc43f86cdd518b14ca0170db)

**Pull request merged**
