### PR TITLE
Fix std::string(NULL) in DataFile.cc

### PR DESCRIPTION
**Pull request by jtbandes**
Per https://en.cppreference.com/w/cpp/string/basic_string/basic_string (5), `s==NULL` is undefined behavior. Just use the default string constructor instead.

I discovered this when I ran into a segmentation fault constructing a DataFileReader from an `avro::istreamInputStream`.

(For such a simple change I didn't bother trying to file a Jira ticket nor changing any unit tests. Let me know if these are necessary and I can put in some more effort 🙂)

### CODE REVIEW

**Comment by Fokko** [comment]
@cutting @thiru-startsmartlabs @thiru-apache My knowledge of c++ is not up to par, can you shed some light on this?

**Comment by jtbandes** [comment]
Bump :)

**Comment by steinio** [comment]
This is also an issue with DataFileWriter

**Comment by jtbandes** [comment]
Any update on this?

**Comment by jtbandes** [comment]
I see one of these was fixed already in https://github.com/apache/avro/pull/520.

**Comment by Fokko** [comment]
Thanks @jtbandes for the PR. I'll release 1.9.1 RC2 tomorrow, please verify.

**Pull request merged**
