### PR TITLE
AVRO-1974: Python3 support for logical types

### PR DESCRIPTION
**Pull request by martinxsliu**
Adds support for all logical types to the Python3 implementation.

### CODE REVIEW

**Comment by rhaarm** [comment]
Any reason this hasn't been merged yet, I just started using Avro and sad to see that this has been waiting for commit over a year. Maybe I should abandon using Avro because it doesn't seem as popular as I thought?

**Comment by barrywhart** [comment]
@rhaarm: You might take a look at the similar `fastavro` library. It has current support for logical types in Python 2, 3, and PyPy.

**Comment by rhaarm** [comment]
@barrywhart I'm shocked, but on fastavro page you have this statement:

> fastavro is less feature complete than avro, however it's much faster.

Also, this part is concerning

> If you're interested in maintaining this package - please drop me a line

**Comment by barrywhart** [comment]
@rhaarm: `fastavro` is not my project, although I have contributed a few recent PRs. It is definitely faster than the `avro` project. I started using Avro about six months ago and switched to it when I compared the performance. Since then, I've done some additional work to speed up in more (especially writes).

The original author of the project is no longer actively maintaining it. I contributed several PRs in November and December, and another developer has also been doing some maintenance. I don't know what the future holds, but the library seems to be in pretty good shape to me. It's got a solid feature set, works on both Python 2 and Python 3, and I don't think Avro is a fast-changing standard anyway.

**Comment by rhaarm** [comment]
@barrywhart thanks for the update

**Comment by kojiromike** [comment]
If you want to fixup the conflicts and get tests passing, then I'm happy to merge this PR, but I'm considering the lang/py3 implementation deprecated in favor of lang/py, which supports Python 3. If you want to improve the implementation of logical types in lang/py, that would also be great.

**Comment by kojiromike** [comment]
Closing this as the lang/py3 implementation is unmaintained. Please use lang/py going forward.

**Pull request closed without merging**
