### PR TITLE
AVRO-2752: PHP: Setup as Composer package on Packagist.org

### PR DESCRIPTION
**Pull request by siad007**
Added composer setup. Once merged it should be submitted on https://packagist.org/
Maybe you want to rename the vendor/projectname in composer.json under the key `name`.

### CODE REVIEW

**Comment by Fokko** [comment]
@siad007 cool stuff. We can do this with the upcoming 1.10 release. Can you fix the merge conflicts?

**Comment by siad007** [comment]
> 
> 
> @siad007 cool stuff. We can do this with the upcoming 1.10 release. Can you fix the merge conflicts?

done

**Comment by fcoedno** [comment]
Is this really fixed? Searching for it in packagist.org I couldn't find the package.

**Comment by siad007** [comment]
There is still an open ticket
https://issues.apache.org/jira/browse/AVRO-2843

Francisco Edno <notifications@github.com> schrieb am Mo. 27. Juli 2020 um
22:41:

**Comment by fcoedno** [comment]
That ticket is open since May, is there any plans on doing that anytime soon? It simply makes it impossible to use this lib in any PHP project :/

**Pull request merged**
