### PR TITLE
AVRO-1954 - Schema.Field.defaultVal() generates: Unknown datum type org.apache.avro.JsonProperties$Null

### PR DESCRIPTION
**Pull request by derekstraka**
Backport the fix for AVRO-1954 to the 1.8 branch

### CODE REVIEW

**Comment by derekstraka** [comment]
I've run into this issue a few times when using the 1.8 branch, so I backported the fix from #180 .  If the 1.8 branch is effectively closed, this PR can be rejected.

**Comment by nandorKollar** [comment]
@derekstraka I cherry-picket and [committed](https://github.com/apache/avro/commit/10792f777f5a31f8c1e5d9a6f6c6d4ba2727ab58) the fix to branch-1.8 and will be release with the next release from 1.8 branch. If it looks good to you, you can close this PR.

**Comment by gopipofficial** [comment]
hi Team,
I'm facing an issue similar to this  can some one help me to fix this? below is the error messsage
"AvroRuntimeException: Unknown datum type org.apache.avro.JsonProperties$Null: org.apache.avro.JsonProperties$Null@7714e963"

**Comment by anhldbk** [comment]
@gopipofficial any sample code?

**Pull request closed without merging**
